# 📊 Data Quality Assessment

### Retail Sales Analysis Project

---

Before we can analyze data or build dashboards, we must first check if our data is **clean and reliable**. This process is called **Data Quality Assessment**.

> _"Garbage In, Garbage Out"_ — If the data is bad, every analysis built on it will be wrong.

---

## 🎯 Learning Objectives

By the end of this session, you will be able to:

1. **Load** an Excel dataset into a Pandas DataFrame
2. **Identify missing values** in a dataset
3. **Detect duplicate records**
4. **Inspect data types** and spot incorrect types
5. **Examine numerical columns** using summary statistics
6. **Examine categorical columns** using value counts
7. **Inspect date columns** and check their format
8. **Verify data consistency** (e.g., Revenue = Price × Quantity)
9. **Create a Data Quality Report** summarizing all findings

---

## 📖 Concept Explanation

### What is Data Quality?

**Data Quality** refers to how accurate, complete, and reliable your data is. Before doing any analysis, we need to answer:

| Question | Why It Matters |
|----------|----------------|
| Are there **missing values**? | Missing data can give wrong averages, wrong counts, and misleading charts |
| Are there **duplicate rows**? | Duplicates inflate numbers — e.g., counting the same sale twice |
| Are the **data types correct**? | A date stored as text cannot be used for time-based analysis |
| Are **numerical values sensible**? | Negative prices or quantities of 0 indicate errors |
| Are **categorical values consistent**? | "Electronics" vs "electronics" vs "ELECTRONICS" are treated as different |
| Is the **data consistent**? | If Revenue should equal Price × Quantity, we must verify it |

### The Data Quality Assessment Workflow

```
Step 1: Load the Data
    ↓
Step 2: Get a Quick Overview (shape, info, head)
    ↓
Step 3: Check for Missing Values
    ↓
Step 4: Check for Duplicate Records
    ↓
Step 5: Inspect Numerical Columns
    ↓
Step 6: Inspect Categorical Columns
    ↓
Step 7: Inspect Date Columns
    ↓
Step 8: Verify Data Consistency
    ↓
Step 9: Write a Data Quality Report
```

---

## 💻 Code Examples

Let's learn each step with clear examples, then apply them to our Sales dataset.

---

### Step 0: Import Required Libraries

In [1]:
# Import pandas — the main library for data analysis in Python
import pandas as pd

# Confirm pandas is loaded
print("Pandas version:", pd.__version__)
print("✅ Libraries loaded successfully!")

Pandas version: 3.0.2
✅ Libraries loaded successfully!


**Expected Output:**
```
Pandas version: 2.x.x
✅ Libraries loaded successfully!
```

---

### Step 1: Load the Dataset

In [2]:
# Load the Excel file into a DataFrame
# pd.read_excel() reads .xlsx files
# We store the result in a variable called 'df' (short for DataFrame)
df = pd.read_excel('DataSet_used\sales_data_messy.xlsx')

# Print a success message with the number of rows and columns
print(f"✅ Dataset loaded successfully!")
print(f"📦 Rows: {df.shape[0]}, Columns: {df.shape[1]}")

<>:4: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:4: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\HP\AppData\Local\Temp\ipykernel_25048\1720975410.py:4: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  df = pd.read_excel('DataSet_used\sales_data_messy.xlsx')


✅ Dataset loaded successfully!
📦 Rows: 110, Columns: 7


**Expected Output:**
```
✅ Dataset loaded successfully!
📦 Rows: 100, Columns: 7
```

---

### Step 2: Quick Overview of the Data

Before diving deep, let's get a **bird's-eye view** of the dataset.

In [3]:
# Display the first 5 rows of the dataset
# .head() shows the top rows — helps us see what the data looks like

print("FIRST 5 ROWS")
df.head()

FIRST 5 ROWS


,Transaction_ID,Date,Product,Category,Price,Quantity,Revenue
0,TXN-1001,2026-01-07,Headphones,Accessories,150.0,2,300
1,TXN-1002,2026-01-20,Smartphone,Electronics,600.0,4,2400
2,TXN-1003,2026-01-29,Smartphone,Electronics,600.0,3,1800
3,TXN-1004,2026-01-15,Headphones,Accessories,150.0,1,150
4,TXN-1005,2026-01-11,Headphones,Accessories,150.0,4,600


**Expected Output:**

| | Transaction_ID | Date | Product | Category | Price | Quantity | Revenue |
|---|---|---|---|---|---|---|---|
| 0 | TXN-1001 | 2026-01-07 | Headphones | Accessories | 150 | 2 | 300 |
| 1 | TXN-1002 | 2026-01-20 | Smartphone | Electronics | 600 | 4 | 2400 |
| 2 | TXN-1003 | 2026-01-29 | Smartphone | Electronics | 600 | 3 | 1800 |
| 3 | TXN-1004 | 2026-01-15 | Headphones | Accessories | 150 | 1 | 150 |
| 4 | TXN-1005 | 2026-01-11 | Headphones | Accessories | 150 | 4 | 600 |

In [4]:
# Display the last 5 rows of the dataset
# .tail() shows the bottom rows — useful to check if data ends properly
print("LAST 5 ROWS")
df.tail()

LAST 5 ROWS


,Transaction_ID,Date,Product,Category,Price,Quantity,Revenue
105,TXN-1040,2026-01-27,NaN,Electronics,1000.0,4,4000
106,TXN-1023,2026-01-02,Laptop,Electronics,1000.0,1,1000
107,TXN-1081,2026-01-08,Headphones,Accessories,150.0,3,450
108,TXN-1011,2026-01-19,Smartphone,Electronics,600.0,2,1200
109,TXN-1001,2026-01-07,Headphones,Accessories,150.0,2,300


In [5]:
# .info() gives a summary of the DataFrame:
# - Number of rows and columns
# - Column names
# - Data types of each column
# - Non-null count (how many values are NOT missing)
print("DATASET INFO")
df.info()

DATASET INFO
<class 'pandas.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Transaction_ID  107 non-null    str    
 1   Date            107 non-null    str    
 2   Product         106 non-null    str    
 3   Category        107 non-null    str    
 4   Price           107 non-null    float64
 5   Quantity        110 non-null    int64  
 6   Revenue         110 non-null    int64  
dtypes: float64(1), int64(2), str(4)
memory usage: 10.1 KB


**Expected Output:**
```
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  100 non-null    object
 1   Date            100 non-null    object    ⬅️ This should be datetime, not object!
 2   Product         100 non-null    object
 3   Category        100 non-null    object
 4   Price           100 non-null    int64
 5   Quantity        100 non-null    int64
 6   Revenue         100 non-null    int64
```

> ⚠️ **Observation:** The `Date` column is stored as `object` (text), not as `datetime`. This is a **data quality issue** we will address!

---

In [6]:
# .columns shows all column names in the dataset
print("Column Names:")
print(df.columns.tolist())

Column Names:
['Transaction_ID', 'Date', 'Product', 'Category', 'Price', 'Quantity', 'Revenue']


**Expected Output:**
```
Column Names:
['Transaction_ID', 'Date', 'Product', 'Category', 'Price', 'Quantity', 'Revenue']
```

---

In [7]:
# .dtypes shows the data type of each column
# Common types:
#   int64   → whole numbers (e.g., 150, 2)
#   float64 → decimal numbers (e.g., 3.14)
#   object  → text/strings (e.g., 'Laptop', '2026-01-07')
print("Data Types of Each Column:")
print(df.dtypes)

Data Types of Each Column:
Transaction_ID        str
Date                  str
Product               str
Category              str
Price             float64
Quantity            int64
Revenue             int64
dtype: object


---

##  Sales Data Quality Assessment

Now let's systematically assess the quality of our **Sales dataset** step by step.

---

### 🔍 1. Check Missing Values

**What are Missing Values?**

Missing values are blank or empty cells in the data. In Python, they appear as `NaN` (Not a Number) or `None`.

**Why are they a problem?**
- They can give wrong averages (e.g., average salary ignoring some employees)
- Many functions crash or give errors with missing data
- Charts and visualizations become misleading

In [8]:
# ---- CHECK MISSING VALUES ----

# .isnull() marks each cell as True (missing) or False (not missing)
# .sum() counts the number of True values per column

missing_values = df.isnull().sum()
print(missing_values)

Transaction_ID    3
Date              3
Product           4
Category          3
Price             3
Quantity          0
Revenue           0
dtype: int64


**Expected Output:**
```
==================================================
MISSING VALUES PER COLUMN
==================================================
Transaction_ID    0
Date              0
Product           0
Category          0
Price             0
Quantity          0
Revenue           0
dtype: int64
```

In [9]:
# Let's also calculate the PERCENTAGE of missing values
# This is more useful when the dataset has thousands of rows
# Formula: (missing count / total rows) * 100
print("\nMISSING VALUES — COUNT & PERCENTAGE")
missing_count = df.isnull().sum()             # Count of missing per column
missing_percent = (missing_count / len(df)) * 100  # Percentage of missing

# Create a summary table
missing_summary = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing %': missing_percent.round(2)  # Round to 2 decimal places
})

print(missing_summary)


MISSING VALUES — COUNT & PERCENTAGE
                Missing Count  Missing %
Transaction_ID              3       2.73
Date                        3       2.73
Product                     4       3.64
Category                    3       2.73
Price                       3       2.73
Quantity                    0       0.00
Revenue                     0       0.00


**Expected Output:**
```
MISSING VALUES — COUNT & PERCENTAGE
--------------------------------------------------
                Missing Count  Missing %
Transaction_ID              0       0.0
Date                        0       0.0
Product                     0       0.0
Category                    0       0.0
Price                       0       0.0
Quantity                    0       0.0
Revenue                     0       0.0
```

> ✅ **Result:** No missing values found! Our dataset is complete.

**Question to Students:** _Are there any missing values? Which columns contain missing values?_

**Answer:** No, there are zero missing values in all 7 columns.

---

### 🔍 2. Check Duplicate Records

**What are Duplicates?**

A duplicate row is an **exact copy** of another row. For example, the same transaction recorded twice.

**Why are they a problem?**
- Revenue gets counted twice → wrong total sales
- Product counts get inflated
- Reports become inaccurate

In [10]:
# ---- CHECK DUPLICATE RECORDS ----

# .duplicated() marks each row as True (duplicate) or False (not duplicate)
# .sum() counts the total number of duplicate rows

duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 10


**Expected Output:**
```
==================================================
DUPLICATE RECORDS CHECK
==================================================
Number of duplicate rows: 0
```

In [11]:
# If duplicates existed, we can VIEW them using:
# df[df.duplicated()] → This filters and shows only the duplicate rows

# Let's check anyway (good practice)
duplicates = df[df.duplicated()]
print(f"Duplicate rows found: {len(duplicates)}")

display(duplicates)

Duplicate rows found: 10


,Transaction_ID,Date,Product,Category,Price,Quantity,Revenue
100,TXN-1084,2026-01-14,Smartphone,Electronics,600.0,4,2400
101,TXN-1054,2026-01-20,Laptop,Electronics,1000.0,1,1000
102,TXN-1071,2026-01-26,Tablet,Electronics,400.0,2,800
103,TXN-1046,2026-01-15,Laptop,Electronics,1000.0,3,3000
104,TXN-1045,2026-01-16,Tablet,Electronics,400.0,4,1600
105,TXN-1040,2026-01-27,NaN,Electronics,1000.0,4,4000
106,TXN-1023,2026-01-02,Laptop,Electronics,1000.0,1,1000
107,TXN-1081,2026-01-08,Headphones,Accessories,150.0,3,450
108,TXN-1011,2026-01-19,Smartphone,Electronics,600.0,2,1200
109,TXN-1001,2026-01-07,Headphones,Accessories,150.0,2,300


In [12]:
# We can also check duplicates based on a SPECIFIC column
# For example: Are there duplicate Transaction IDs?
# Each transaction should have a UNIQUE ID

txn_duplicates = df.duplicated(subset=['Transaction_ID']).sum()
print(f"Duplicate Transaction IDs: {txn_duplicates}")

if txn_duplicates == 0:
    print("✅ All Transaction IDs are unique!")
else:
    print("⚠️ Warning: Some Transaction IDs are repeated!")
df.drop_duplicates(inplace=True)

Duplicate Transaction IDs: 12
⚠️ Warning: Some Transaction IDs are repeated!


**Expected Output:**
```
Duplicate Transaction IDs: 0
✅ All Transaction IDs are unique!
```

> ✅ **Result:** No duplicate records found. Each transaction is unique.

**Questions to Students:**
- _How many duplicate rows exist?_ → 0
- _Should duplicate rows be removed?_ → Yes, generally duplicates should be removed unless there's a valid reason.

---

### 🔍 3. Inspect Numerical Columns

**What are Numerical Columns?**

Columns that contain numbers — like `Price`, `Quantity`, and `Revenue`.

**What to look for:**
- Are there **negative values** where they shouldn't be? (e.g., negative Price)
- Are there **zero values** that don't make sense? (e.g., Quantity = 0)
- Are there **extreme outliers**? (e.g., a laptop costing ₹1,00,000 when others cost ₹1,000)
- Do **min and max values** make sense?

In [13]:
# ---- INSPECT NUMERICAL COLUMNS ----

# .describe() gives summary statistics for numerical columns:
#   count → number of non-null values
#   mean  → average value
#   std   → standard deviation (how spread out values are)
#   min   → minimum value
#   25%   → 25th percentile (Q1)
#   50%   → median (middle value)
#   75%   → 75th percentile (Q3)
#   max   → maximum value

print("=" * 50)
print("NUMERICAL COLUMN STATISTICS")
print("=" * 50)
df.describe()

NUMERICAL COLUMN STATISTICS


,Price,Quantity,Revenue
count,97.000000,100.000000,100.000000
mean,473.195876,2.710000,1358.000000
std,329.382460,1.335566,1236.047791
min,150.000000,1.000000,150.000000
25%,200.000000,1.000000,450.000000
50%,400.000000,3.000000,800.000000
75%,600.000000,4.000000,2000.000000
max,1000.000000,5.000000,5000.000000


**Expected Output:**

|       | Price    | Quantity  | Revenue    |
|-------|----------|-----------|------------|
| count | 100.00   | 100.00    | 100.00     |
| mean  | 481.00   | 2.71      | 1358.00    |
| std   | 333.92   | 1.34      | 1236.05    |
| min   | 150.00   | 1.00      | 150.00     |
| 25%   | 200.00   | 1.00      | 450.00     |
| 50%   | 400.00   | 3.00      | 800.00     |
| 75%   | 700.00   | 4.00      | 2000.00    |
| max   | 1000.00  | 5.00      | 5000.00    |

In [14]:
# Let's analyze each numerical column individually

# --- PRICE column ---
print("📌 PRICE Analysis")
print("-" * 35)
print(f"  Minimum Price : ₹{df['Price'].min()}")
print(f"  Maximum Price : ₹{df['Price'].max()}")
print(f"  Average Price : ₹{df['Price'].mean():.2f}")  # .2f means 2 decimal places
print(f"  Negative Prices: {(df['Price'] < 0).sum()}")  # Count negative values
print(f"  Zero Prices    : {(df['Price'] == 0).sum()}")  # Count zero values

print()

# --- QUANTITY column ---
print("📌 QUANTITY Analysis")
print("-" * 35)
print(f"  Minimum Quantity : {df['Quantity'].min()}")
print(f"  Maximum Quantity : {df['Quantity'].max()}")
print(f"  Average Quantity : {df['Quantity'].mean():.2f}")
print(f"  Negative Quantities: {(df['Quantity'] < 0).sum()}")
print(f"  Zero Quantities    : {(df['Quantity'] == 0).sum()}")

print()

# --- REVENUE column ---
print("📌 REVENUE Analysis")
print("-" * 35)
print(f"  Minimum Revenue : ₹{df['Revenue'].min()}")
print(f"  Maximum Revenue : ₹{df['Revenue'].max()}")
print(f"  Average Revenue : ₹{df['Revenue'].mean():.2f}")
print(f"  Negative Revenue: {(df['Revenue'] < 0).sum()}")
print(f"  Zero Revenue    : {(df['Revenue'] == 0).sum()}")

📌 PRICE Analysis
-----------------------------------
  Minimum Price : ₹150.0
  Maximum Price : ₹1000.0
  Average Price : ₹473.20
  Negative Prices: 0
  Zero Prices    : 0

📌 QUANTITY Analysis
-----------------------------------
  Minimum Quantity : 1
  Maximum Quantity : 5
  Average Quantity : 2.71
  Negative Quantities: 0
  Zero Quantities    : 0

📌 REVENUE Analysis
-----------------------------------
  Minimum Revenue : ₹150
  Maximum Revenue : ₹5000
  Average Revenue : ₹1358.00
  Negative Revenue: 0
  Zero Revenue    : 0


**Expected Output:**
```
📌 PRICE Analysis
-----------------------------------
  Minimum Price : ₹150
  Maximum Price : ₹1000
  Average Price : ₹481.00
  Negative Prices: 0
  Zero Prices    : 0

📌 QUANTITY Analysis
-----------------------------------
  Minimum Quantity : 1
  Maximum Quantity : 5
  Average Quantity : 2.71
  Negative Quantities: 0
  Zero Quantities    : 0

📌 REVENUE Analysis
-----------------------------------
  Minimum Revenue : ₹150
  Maximum Revenue : ₹5000
  Average Revenue : ₹1358.00
  Negative Revenue: 0
  Zero Revenue    : 0
```

> ✅ **Result:** All numerical values are positive and within sensible ranges. No anomalies detected.

**Questions to Students:**
- _What is the minimum Sales value?_ → ₹150
- _What is the maximum Sales value?_ → ₹5000
- _What is the average Profit?_ → ₹1358.00 (Revenue)
- _What is the maximum Discount?_ → Not applicable (no Discount column in this dataset)

---

### 🔍 4. Inspect Categorical Columns

**What are Categorical Columns?**

Columns that contain **text or labels** — like `Product`, `Category`, and `Transaction_ID`.

**What to look for:**
- How many **unique values** are there?
- Are there **inconsistent names**? (e.g., "laptop" vs "Laptop" vs "LAPTOP")
- Which value appears **most/least often**?
- Are there any **unexpected values**?

In [15]:
# ---- INSPECT CATEGORICAL COLUMNS ----

# .nunique() tells us how many UNIQUE values each column has
print("=" * 50)
print("UNIQUE VALUE COUNTS")
print("=" * 50)
print(f"  Transaction_ID : {df['Transaction_ID'].nunique()} unique values")
print(f"  Product        : {df['Product'].nunique()} unique values")
print(f"  Category       : {df['Category'].nunique()} unique values")
print(f"  Date           : {df['Date'].nunique()} unique values")

UNIQUE VALUE COUNTS
  Transaction_ID : 97 unique values
  Product        : 5 unique values
  Category       : 2 unique values
  Date           : 30 unique values


In [16]:
# .value_counts() shows how many times each value appears
# Let's check the PRODUCT column

print("=" * 50)
print("PRODUCT — Value Counts")
print("=" * 50)
print(df['Product'].value_counts())

print()

# Now the CATEGORY column
print("=" * 50)
print("CATEGORY — Value Counts")
print("=" * 50)
print(df['Category'].value_counts())

PRODUCT — Value Counts
Product
Laptop        23
Headphones    22
Tablet        20
Smartwatch    19
Smartphone    13
Name: count, dtype: int64

CATEGORY — Value Counts
Category
Electronics    56
Accessories    41
Name: count, dtype: int64


**Expected Output:**
```
==================================================
PRODUCT — Value Counts
==================================================
Laptop        25
Headphones    22
Smartwatch    20
Tablet        20
Smartphone    13

==================================================
CATEGORY — Value Counts
==================================================
Electronics    58
Accessories    42
```

In [17]:
# Check for inconsistent naming
# If 'Laptop' and 'laptop' both exist, they would be counted separately!

print("=" * 50)
print("CHECKING FOR NAMING INCONSISTENCIES")
print("=" * 50)

# List all unique product names
print("\nUnique Products:", df['Product'].unique())

# List all unique category names
print("Unique Categories:", df['Category'].unique())

# If names were inconsistent, we might see:
# ['Laptop', 'laptop', 'LAPTOP'] — three entries for the same thing!
print("\n✅ All product and category names look consistent!")

CHECKING FOR NAMING INCONSISTENCIES

Unique Products: <ArrowStringArray>
['Headphones', 'Smartphone', 'Laptop', 'Smartwatch', 'Tablet', nan]
Length: 6, dtype: str
Unique Categories: <ArrowStringArray>
['Accessories', 'Electronics', nan]
Length: 3, dtype: str

✅ All product and category names look consistent!


**Questions to Students:**
- _Which product has the most records?_ → Laptop (25)
- _Which category appears most frequently?_ → Electronics (58)
- _Which product has the fewest records?_ → Smartphone (13)

---

### 🔍 5. Inspect Date Columns

**Why check Date columns?**

Dates are often loaded as **text (object type)** instead of **datetime**. If dates are stored as text:
- You CANNOT sort by date properly
- You CANNOT extract month, year, day of week
- You CANNOT do time-based analysis (e.g., monthly sales trends)

In [18]:
# ---- INSPECT DATE COLUMN ----

# First, let's check the current data type of the Date column
print("=" * 50)
print("DATE COLUMN INSPECTION")
print("=" * 50)
print(f"Data type of 'Date' column: {df['Date'].dtype}")

# Show the first few date values
print(f"\nSample date values:")
print(df['Date'].head())

DATE COLUMN INSPECTION
Data type of 'Date' column: str

Sample date values:
0    2026-01-07
1    2026-01-20
2    2026-01-29
3    2026-01-15
4    2026-01-11
Name: Date, dtype: str


**Expected Output:**
```
==================================================
DATE COLUMN INSPECTION
==================================================
Data type of 'Date' column: object

Sample date values:
0    2026-01-07
1    2026-01-20
2    2026-01-29
3    2026-01-15
4    2026-01-11
Name: Date, dtype: object
```

> ⚠️ **Issue Found:** The Date column has dtype `object` — meaning it is stored as **text**, not as a proper **datetime** type.

In [19]:
# ---- FIX: Convert Date column from text to datetime ----

# pd.to_datetime() converts text dates into proper datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Verify the conversion
print(f"Data type AFTER conversion: {df['Date'].dtype}")
# print(f"\nDate Range: {df['Date'].min()} to {df['Date'].max()}")
# print(f"\n✅ Date column successfully converted to datetime!")

Data type AFTER conversion: datetime64[us]


**Expected Output:**
```
Data type AFTER conversion: datetime64[ns]

Date Range: 2026-01-01 to 2026-01-31

✅ Date column successfully converted to datetime!
```

> ✅ **Result:** The Date column is now a proper datetime type. We can now extract months, days, and do time-based analysis.

**Questions to Students:**
- _Are dates stored as text or datetime?_ → They were stored as text (object), now converted to datetime.
- _Will conversion be required later?_ → We already did it! Always convert dates early.

---

### 🔍 6. Verify Data Consistency

**What is Data Consistency?**

Data consistency means values across columns should **logically agree with each other**.

In our dataset: **Revenue should always equal Price × Quantity**

If `Revenue ≠ Price × Quantity`, it means there's a calculation error in the data.

In [20]:
# ---- VERIFY DATA CONSISTENCY ----

# Check if Revenue = Price × Quantity for every row
# Create a new column with the expected revenue
df['Expected_Revenue'] = df['Price'] * df['Quantity']

# Compare actual Revenue with Expected Revenue
# If they don't match, there's a data quality issue
mismatches = df[df['Revenue'] != df['Expected_Revenue']]

print("=" * 50)
print("DATA CONSISTENCY CHECK")
print("=" * 50)
print(f"Mismatches found  : {len(mismatches)}")

if len(mismatches) == 0:
    print("\n✅ All Revenue values are consistent (Revenue = Price × Quantity)")
else:
    print("\n⚠️ Inconsistent rows found:")
    print(mismatches[[ 'Price', 'Quantity', 'Revenue', 'Expected_Revenue']])

DATA CONSISTENCY CHECK
Mismatches found  : 3

⚠️ Inconsistent rows found:
    Price  Quantity  Revenue  Expected_Revenue
36    NaN         3     3000               NaN
66    NaN         1      200               NaN
88    NaN         3     3000               NaN


In [21]:
# Clean up: Remove the helper column we created
df.drop(columns=['Expected_Revenue'],inplace=True)

print("✅ Helper column removed. DataFrame is clean.")
print(f"Current columns: {df.columns.tolist()}")

✅ Helper column removed. DataFrame is clean.
Current columns: ['Transaction_ID', 'Date', 'Product', 'Category', 'Price', 'Quantity', 'Revenue']


> ✅ **Result:** Revenue = Price × Quantity for all 100 rows. The data is consistent!

---

## 📋 Data Quality Report

Now let's combine everything into a **professional Data Quality Report**.

This is what you would submit to your manager or include in your project documentation.

In [22]:
# ============================================================
#                  DATA QUALITY REPORT
# ============================================================

print("╔" + "═" * 58 + "╗")
print("║" + "  📋 DATA QUALITY REPORT — Sales Dataset".ljust(58) + "║")
print("╠" + "═" * 58 + "╣")

# --- 1. Dataset Overview ---
print("║" + "  1. DATASET OVERVIEW".ljust(58) + "║")
print("║" + f"     Total Rows    : {df.shape[0]}".ljust(58) + "║")
print("║" + f"     Total Columns : {df.shape[1]}".ljust(58) + "║")
print("║" + "".ljust(58) + "║")

# --- 2. Missing Values Summary ---
print("║" + "  2. MISSING VALUES SUMMARY".ljust(58) + "║")
total_missing = df.isnull().sum().sum()  # Total missing across ALL columns
print("║" + f"     Total Missing Values : {total_missing}".ljust(58) + "║")
if total_missing == 0:
    print("║" + "     Status: ✅ No missing values".ljust(58) + "║")
else:
    print("║" + "     Status: ⚠️ Missing values detected".ljust(58) + "║")
print("║" + "".ljust(58) + "║")

# --- 3. Duplicate Records Summary ---
print("║" + "  3. DUPLICATE RECORDS SUMMARY".ljust(58) + "║")
dup_count = df.duplicated().sum()
print("║" + f"     Duplicate Rows : {dup_count}".ljust(58) + "║")
if dup_count == 0:
    print("║" + "     Status: ✅ No duplicates".ljust(58) + "║")
else:
    print("║" + "     Status: ⚠️ Duplicates found".ljust(58) + "║")
print("║" + "".ljust(58) + "║")

# --- 4. Numerical Column Observations ---
print("║" + "  4. NUMERICAL COLUMN OBSERVATIONS".ljust(58) + "║")
print("║" + f"     Price range    : ₹{df['Price'].min()} — ₹{df['Price'].max()}".ljust(58) + "║")
print("║" + f"     Quantity range : {df['Quantity'].min()} — {df['Quantity'].max()}".ljust(58) + "║")
print("║" + f"     Revenue range  : ₹{df['Revenue'].min()} — ₹{df['Revenue'].max()}".ljust(58) + "║")
neg_vals = ((df['Price'] < 0).sum() + (df['Quantity'] < 0).sum() + (df['Revenue'] < 0).sum())
print("║" + f"     Negative values: {neg_vals}".ljust(58) + "║")
print("║" + "     Status: ✅ All values in valid range".ljust(58) + "║")
print("║" + "".ljust(58) + "║")

# --- 5. Categorical Column Observations ---
print("║" + "  5. CATEGORICAL COLUMN OBSERVATIONS".ljust(58) + "║")
print("║" + f"     Unique Products   : {df['Product'].nunique()}".ljust(58) + "║")
print("║" + f"     Unique Categories : {df['Category'].nunique()}".ljust(58) + "║")
print("║" + "     Status: ✅ Naming is consistent".ljust(58) + "║")
print("║" + "".ljust(58) + "║")

# --- 6. Date Column Observations ---
print("║" + "  6. DATE COLUMN OBSERVATIONS".ljust(58) + "║")
print("║" + f"     Date dtype     : {df['Date'].dtype}".ljust(58) + "║")
print("║" + f"     Date range     : {df['Date'].min().date()} to {df['Date'].max().date()}".ljust(58) + "║")
print("║" + "     Status: ✅ Converted to datetime".ljust(58) + "║")

print("╠" + "═" * 58 + "╣")
print("║" + "  📊 OVERALL STATUS: DATA IS CLEAN & READY ✅".ljust(58) + "║")
print("╚" + "═" * 58 + "╝")

╔══════════════════════════════════════════════════════════╗
║  📋 DATA QUALITY REPORT — Sales Dataset                   ║
╠══════════════════════════════════════════════════════════╣
║  1. DATASET OVERVIEW                                     ║
║     Total Rows    : 100                                  ║
║     Total Columns : 7                                    ║
║                                                          ║
║  2. MISSING VALUES SUMMARY                               ║
║     Total Missing Values : 15                            ║
║     Status: ⚠️ Missing values detected                   ║
║                                                          ║
║  3. DUPLICATE RECORDS SUMMARY                            ║
║     Duplicate Rows : 0                                   ║
║     Status: ✅ No duplicates                              ║
║                                                          ║
║  4. NUMERICAL COLUMN OBSERVATIONS                        ║
║     Price range    : ₹

---

## ⚠️ Common Mistakes

Here are mistakes beginners commonly make when assessing data quality.

---

### ❌ Mistake 1: Using `.isnull()` without `.sum()`

In [23]:
# ❌ WRONG — This shows True/False for EVERY cell (huge output!)
# df.isnull()          # Shows a table of True/False — not useful

# ✅ CORRECT — This gives the COUNT of missing values per column
print("✅ Correct way to check missing values:")
print(df.isnull().sum())

✅ Correct way to check missing values:
Transaction_ID    3
Date              3
Product           3
Category          3
Price             3
Quantity          0
Revenue           0
dtype: int64


---

### ❌ Mistake 2: Forgetting to convert Date column

In [24]:
# ❌ WRONG — Trying to extract month from a text column
# This would give an error if Date is still 'object' type:
# df['Date'].dt.month   → AttributeError!

# ✅ CORRECT — First convert, then extract
# df['Date'] = pd.to_datetime(df['Date'])  # Convert first (already done above)

# Now we can safely extract month
print("✅ Extracting month after conversion:")
print(df['Date'].dt.month.head())

✅ Extracting month after conversion:
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: Date, dtype: float64


---

### ❌ Mistake 3: Confusing `.duplicated()` and `.drop_duplicates()`

In [25]:
# .duplicated() → Returns True/False for each row (used to CHECK)
# .drop_duplicates() → Returns a new DataFrame WITHOUT duplicate rows (used to REMOVE)

# ❌ WRONG — Using drop_duplicates() just to count duplicates
# len(df) - len(df.drop_duplicates())   # Works but is roundabout

# ✅ CORRECT — Use .duplicated().sum() to count
print(f"✅ Number of duplicates: {df.duplicated().sum()}")
print("\nUse .duplicated().sum() to COUNT")
print("Use .drop_duplicates() to REMOVE")

✅ Number of duplicates: 0

Use .duplicated().sum() to COUNT
Use .drop_duplicates() to REMOVE


---

### ❌ Mistake 4: Not checking data types before analysis

In [26]:
# ❌ WRONG — Jumping straight into analysis without checking types
# df['Price'].mean()  → This works, but what if Price was stored as text?

# ✅ CORRECT — Always check dtypes first
print("✅ Always check data types before analysis:")
print(df.dtypes)
print("\n💡 TIP: Run df.dtypes or df.info() BEFORE doing any calculations!")

✅ Always check data types before analysis:
Transaction_ID               str
Date              datetime64[us]
Product                      str
Category                     str
Price                    float64
Quantity                   int64
Revenue                    int64
dtype: object

💡 TIP: Run df.dtypes or df.info() BEFORE doing any calculations!


---

### ❌ Mistake 5: Using `=` instead of `==` for comparison

In [27]:
# ❌ WRONG — Using single = (this ASSIGNS a value, doesn't compare!)
# df['Price'] = 0     → This would SET all prices to 0!

# ✅ CORRECT — Using double == (this COMPARES values)
zero_prices = (df['Price'] == 0).sum()   # This COUNTS rows where Price is 0
print(f"✅ Rows where Price equals 0: {zero_prices}")

print("\n💡 REMEMBER:")
print("   =  means ASSIGN (set a value)")
print("   == means COMPARE (check if equal)")

✅ Rows where Price equals 0: 0

💡 REMEMBER:
   =  means ASSIGN (set a value)
   == means COMPARE (check if equal)


---

## 📝 Practice Tasks

Complete the following tasks using the `sales_data.xlsx` dataset. Try each task on your own before looking at the solution.

---

### Task 1: Find the total number of rows and columns in the dataset

In [28]:
# Task 1: Find total rows and columns
# Hint: Use df.shape

# Write your code below:
print("Rows :",df.shape[0])
print("Cols :",df.shape[1])


Rows : 100
Cols : 7


In [29]:
# ✅ Solution — Task 1
print(f"Total Rows: {df.shape[0]}")
print(f"Total Columns: {df.shape[1]}")

Total Rows: 100
Total Columns: 7


---

### Task 2: Check if there are any missing values in the 'Product' column

In [30]:
# ✅ Solution — Task 2
print(df.isnull().sum())
missing_product = df['Product'].isnull().sum()
print(f"Missing values in 'Product' column: {missing_product}")

Transaction_ID    3
Date              3
Product           3
Category          3
Price             3
Quantity          0
Revenue           0
dtype: int64
Missing values in 'Product' column: 3


---

### Task 3: Find the total number of duplicate rows

In [31]:
# Task 3: Count duplicate rows
print("Duplicate rows:",df.duplicated().sum())

Duplicate rows: 0


---

### Task 4: Find the most sold product (the product with the highest number of transactions)

In [32]:
# ✅ Solution — Task 4
print("Product Transaction Counts:")
print(df['Product'].value_counts())
print(f"\nMost sold product: {df['Product'].value_counts().index[0]}")

Product Transaction Counts:
Product
Laptop        23
Headphones    22
Tablet        20
Smartwatch    19
Smartphone    13
Name: count, dtype: int64

Most sold product: Laptop


---

### Task 5: Check the data type of each column

In [33]:
# ✅ Solution — Task 5
print("Data Types:")
print(df.dtypes)

Data Types:
Transaction_ID               str
Date              datetime64[us]
Product                      str
Category                     str
Price                    float64
Quantity                   int64
Revenue                    int64
dtype: object


---

### Task 6: Find the minimum and maximum values of the 'Revenue' column

In [34]:
# ✅ Solution — Task 6
print(f"Minimum Revenue: ₹{df['Revenue'].min()}")
print(f"Maximum Revenue: ₹{df['Revenue'].max()}")

Minimum Revenue: ₹150
Maximum Revenue: ₹5000


---

### Task 7: Check how many transactions belong to each Category

In [35]:
# ✅ Solution — Task 7
print("Transactions per Category:")
print(df['Category'].value_counts())

Transactions per Category:
Category
Electronics    56
Accessories    41
Name: count, dtype: int64


---

### Task 8: Check if any Price values are negative

In [36]:
# ✅ Solution — Task 8
negative_prices = (df['Price'] < 0).sum()
print(f"Negative Price values: {negative_prices}")

if negative_prices == 0:
    print("✅ No negative prices found!")
else:
    print("⚠️ Negative prices detected — investigate!")

Negative Price values: 0
✅ No negative prices found!


---

### Task 9: Find the date range of the dataset (earliest and latest date)

In [37]:
# ✅ Solution — Task 9
print(f"Earliest Date: {df['Date'].min().date()}")
print(f"Latest Date  : {df['Date'].max().date()}")
print(f"Date Span    : {(df['Date'].max() - df['Date'].min()).days} days")

Earliest Date: 2026-01-01
Latest Date  : 2026-01-31
Date Span    : 30 days


---

### Task 10: Verify that Revenue = Price × Quantity for all rows

In [38]:
# ✅ Solution — Task 10
# Calculate expected revenue
expected = df['Price'] * df['Quantity']

# Count mismatches
mismatches = (df['Revenue'] != expected).sum()
print(f"Rows where Revenue ≠ Price × Quantity: {mismatches}")

if mismatches == 0:
    print("✅ All revenue values are consistent!")
else:
    print(f"⚠️ {mismatches} inconsistent rows found!")

Rows where Revenue ≠ Price × Quantity: 3
⚠️ 3 inconsistent rows found!


---

## 📝 Assignment

Complete the following assignment after class. Submit your notebook with all cells executed.

---

### Assignment: Create Your Own Data Quality Report

Write code to create a **complete Data Quality Report** that prints the following:

1. **Dataset Shape** — Total rows and columns
2. **Missing Values Summary** — Missing count & percentage for each column
3. **Duplicate Records Count** — Number of exact duplicate rows
4. **Numerical Summary** — Min, Max, Mean for Price, Quantity, Revenue
5. **Categorical Summary** — Unique values and most common value for Product and Category
6. **Date Summary** — Data type, earliest date, latest date
7. **Consistency Check** — Verify Revenue = Price × Quantity

**Bonus:** Format the output neatly using print statements with divider lines.

---

In [ ]:
# ============================================================
#              ASSIGNMENT: DATA QUALITY REPORT
# ============================================================
# Load the dataset
df = pd.read_excel("DataSet_used\\sales_data_messy.xlsx")
# 1. Dataset Shape
print("\nShape of Dataset")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

# 2. Missing Values Summary (count and percentage for each column)
print("\nMISSING VALUES — COUNT & PERCENTAGE")
missing_count = df.isnull().sum()  
missing_percent = (missing_count / len(df)) * 100  

missing_summary = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing %': missing_percent.round(2)})
print(missing_summary)

# 3. Duplicate Records Count
print("\nDuplicate rows:",df.duplicated().sum())

# 4. Numerical Summary (Min, Max, Mean for Price, Quantity, Revenue)
print("\nPrice Analysis")
print("="*30)
print("Minimum Price: Rs.", df['Price'].min())
print("Maximum Price: Rs.", df['Price'].max())
print("Average Price: Rs.", round(df['Price'].mean(),2))
print("Negative Prices: Rs.", (df['Price'] < 0).sum())
print("Zero Prices:", (df['Price'] == 0).min().sum())
print("="*30)
print("\n")
print("Quantity Analysis")
print("="*30)
print("Minimum Quantity:", df['Quantity'].min())
print("Maximum Quantity:", df['Quantity'].max())
print("Average Quantity:", round(df['Quantity'].mean(),2))
print("Negative Quantities:", (df['Quantity'] < 0).sum())
print("Zero Quantities:", (df['Quantity'] == 0).min().sum())
print("="*30)
print("\n")
print("Revenue Analysis")
print("="*30)
print("Minimum Revenue:", df['Revenue'].min())
print("Maximum Revenue:", df['Revenue'].max())
print("Average Revenue:", round(df['Revenue'].mean(),2))
print("Negative Revenue:", (df['Revenue'] < 0).sum())
print("Zero Revenue:", (df['Revenue'] == 0).min().sum())
print("="*30)

# 5. Categorical Summary (Unique counts & most common value)
print("\nCategorical Summary")
print("Unique counts :",df['Category'].nunique())
print("\nMost common values :\n",df["Category"].value_counts())

# 6. Date Summary (dtype, min date, max date)
# Write your code below:
print("\nDate Summary\n")
df["Date"] = pd.to_datetime(df["Date"])
print("Datatype of Date:",df["Date"].dtype)
print("Minimum date in dataset:", df["Date"].min().date())
print("Maximum date in dataset:", df["Date"].max().date())
print("Time span:", df["Date"].max().date() - df["Date"].min().date())

# 7. Consistency Check (Revenue = Price × Quantity)
print("\nConsistency Check (Revenue = Price × Quantity)")
df["Expected_Revenue"] = df["Price"] * df["Quantity"]
mismatch = df[df["Expected_Revenue"] != df['Revenue']]
print("TOTAL MISMATCHES:",len(mismatch))
print()
display(mismatch[["Date", "Category", "Product", "Revenue", "Expected_Revenue"]])


Shape of Dataset
Rows: 110
Columns: 7

MISSING VALUES — COUNT & PERCENTAGE
                Missing Count  Missing %
Transaction_ID              3       2.73
Date                        3       2.73
Product                     4       3.64
Category                    3       2.73
Price                       3       2.73
Quantity                    0       0.00
Revenue                     0       0.00

Duplicate rows: 10

Price Analysis
Minimum Price: Rs. 150.0
Maximum Price: Rs. 1000.0
Average Price: Rs. 487.85
Negative Prices: Rs. 0
Zero Prices: 0


Quantity Analysis
Minimum Quantity: 1
Maximum Quantity: 5
Average Quantity: 2.7
Negative Quantities: 0
Zero Quantities: 0


Revenue Analysis
Minimum Revenue: 150
Maximum Revenue: 5000
Average Revenue: 1377.73
Negative Revenue: 0
Zero Revenue: 0

Categorical Summary
Unique counts : 2

Most common values :
 Category
Electronics    64
Accessories    43
Name: count, dtype: int64

Date Summary

Datatype of Date: datetime64[us]
Minimum date in d

,Date,Category,Product,Revenue,Expected_Revenue
36,2026-01-25,Electronics,Laptop,3000,NaN
66,2026-01-14,Accessories,Smartwatch,200,NaN
88,2026-01-04,Electronics,Laptop,3000,NaN


---

## 🔑 Key Takeaways

| # | Takeaway | Pandas Function |
|---|----------|----------------|
| 1 | Always inspect your data **before** analyzing it | `df.head()`, `df.info()`, `df.shape` |
| 2 | Check for **missing values** — they distort results | `df.isnull().sum()` |
| 3 | Check for **duplicate rows** — they inflate numbers | `df.duplicated().sum()` |
| 4 | Verify **data types** — especially dates | `df.dtypes`, `pd.to_datetime()` |
| 5 | Inspect **numerical columns** for invalid values | `df.describe()`, `(df['col'] < 0).sum()` |
| 6 | Inspect **categorical columns** for consistency | `df['col'].value_counts()`, `df['col'].unique()` |
| 7 | Verify **data consistency** across columns | Compare calculated vs actual values |
| 8 | Document findings in a **Data Quality Report** | Combine all checks into one summary |

---

### 🔮 What's Next?

In the next session, we will learn **Data Cleaning** — how to actually **fix** the issues found during quality assessment:
- Handling missing values (fill or drop)
- Removing duplicates
- Fixing data types
- Standardizing categorical values

---

> 💡 **Remember:** _"A data scientist spends 80% of their time cleaning data. Data Quality Assessment is the first step!"_

---

**End of Session | Data Quality Assessment** 📊