# 🧹 Data Cleaning

### Retail Sales Analysis Project

---

**Data Cleaning** is the process of detecting and correcting (or removing) corrupt, inaccurate, or irrelevant records from the dataset.

> _"80% of a Data Scientist's time is spent cleaning data."_ — Common industry saying

---

## 🎯 Learning Objectives

By the end of this session, you will be able to:

1. **Handle missing values** using `dropna()` and `fillna()` with different strategies
2. **Remove duplicate records** using `drop_duplicates()`
3. **Fix data types** — convert strings to dates using `pd.to_datetime()`
4. **Clean text columns** — remove extra spaces, fix inconsistent casing
5. **Verify the cleaned dataset** — confirm all issues have been resolved
6. **Build a complete Data Cleaning Pipeline** from start to finish

---

## 📖 Concept Explanation

### What is Data Cleaning?

**Data Cleaning** (also called Data Wrangling) is the process of fixing or removing **incorrect, incomplete, duplicate, or improperly formatted** data in a dataset.

Think of it like this:

| Real World Analogy | Data Cleaning Equivalent |
|---|---|
| Washing vegetables before cooking | Removing errors before analysis |
| Removing rotten fruits from a basket | Dropping corrupt or duplicate rows |
| Filling a blank field in a form | Filling missing values with sensible defaults |
| Correcting a misspelled name | Standardizing text (e.g., fixing case, trimming spaces) |

### Why is Data Cleaning Important?

| Problem | Consequence if NOT cleaned |
|---|---|
| Missing values | Wrong averages, broken calculations |
| Duplicate rows | Sales counted twice → inflated revenue |
| Wrong data types | Dates stored as text → cannot sort by date |
| Inconsistent text | "Electronics" ≠ "electronics" ≠ " Electronics " → treated as 3 different categories |

### Assessment vs. Cleaning

| Data Quality Assessment (Previous Lesson) | Data Cleaning (This Lesson) |
|---|---|
| **Find** the problems | **Fix** the problems |
| `df.isnull().sum()` → "There are 5 missing values" | `df.fillna(value)` → "Fill those 5 missing values" |
| `df.duplicated().sum()` → "There are 3 duplicates" | `df.drop_duplicates()` → "Remove those 3 duplicates" |
| `df.dtypes` → "Date is stored as text" | `pd.to_datetime()` → "Convert text to proper date" |

### The Data Cleaning Workflow

```
Step 1: Load the Data
    ↓
Step 2: Assess the Data (Quick Overview)
    ↓
Step 3: Handle Missing Values (fillna / dropna)
    ↓
Step 4: Remove Duplicate Records (drop_duplicates)
    ↓
Step 5: Fix Data Types (to_datetime / astype)
    ↓
Step 6: Clean Text Columns (strip / lower / title)
    ↓
Step 7: Verify the Cleaned Dataset
    ↓
✅ Clean Data Ready for Analysis!
```

---

## 💻 Code Examples

We will use `sales_data_messy.xlsx` — a real-world messy version of our Sales dataset — to learn every cleaning technique hands-on.

---

### Step 0: Import Required Libraries

In [30]:
# Import pandas — the main library for data analysis in Python
import pandas as pd

# Import numpy — needed for NaN (Not a Number) values
import numpy as np

# Confirm libraries are loaded
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("✅ Libraries loaded successfully!")

Pandas version: 3.0.2
NumPy version: 2.4.4
✅ Libraries loaded successfully!


**Expected Output:**
```
Pandas version: 2.x.x
NumPy version: 1.x.x
✅ Libraries loaded successfully!
```

---

### Step 1: Load the Messy Dataset & Understand Its Problems

In the real world, data rarely comes perfectly clean. Our `sales_data_messy.xlsx` file has **real data quality problems** — missing values, duplicate rows, and incorrect data types.

In [31]:
# ---- LOAD THE MESSY SALES DATASET ----

# Read the messy Excel file into a DataFrame
df = pd.read_excel('DataSet_used\\sales_data_messy.xlsx')

# Quick overview of the dataset
print("📦 MESSY SALES DATASET LOADED")
print("=" * 50)
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")
print(f"Column names: ",df.columns.to_list())

# Display the first 10 rows
print("\nFirst 10 rows:")
df.head(10)

📦 MESSY SALES DATASET LOADED
Rows: 110
Columns: 7
Column names:  ['Transaction_ID', 'Date', 'Product', 'Category', 'Price', 'Quantity', 'Revenue']

First 10 rows:


,Transaction_ID,Date,Product,Category,Price,Quantity,Revenue
0,TXN-1001,2026-01-07,Headphones,Accessories,150.0,2,300
1,TXN-1002,2026-01-20,Smartphone,Electronics,600.0,4,2400
2,TXN-1003,2026-01-29,Smartphone,Electronics,600.0,3,1800
3,TXN-1004,2026-01-15,Headphones,Accessories,150.0,1,150
4,TXN-1005,2026-01-11,Headphones,Accessories,150.0,4,600
5,TXN-1006,2026-01-08,Laptop,Electronics,1000.0,1,1000
6,TXN-1007,2026-01-29,Smartwatch,Accessories,200.0,1,200
7,TXN-1008,2026-01-21,Smartwatch,Accessories,200.0,2,400
8,TXN-1009,2026-01-07,Smartphone,Electronics,600.0,4,2400
9,TXN-1010,NaN,Smartwatch,Accessories,200.0,4,800


**Expected Output:**
```
📦 MESSY SALES DATASET LOADED
==================================================
Rows: 110
Columns: 7
Column names: ['Transaction_ID', 'Date', 'Product', 'Category', 'Price', 'Quantity', 'Revenue']
```

| | Transaction_ID | Date | Product | Category | Price | Quantity | Revenue |
|---|---|---|---|---|---|---|---|
| 0 | TXN-1001 | 2026-01-07 | Headphones | Accessories | 150.0 | 2 | 300 |
| 1 | TXN-1002 | 2026-01-20 | Smartphone | Electronics | 600.0 | 4 | 2400 |
| ... | ... | ... | ... | ... | ... | ... | ... |
| 9 | TXN-1010 | **NaN** | Smartwatch | Accessories | 200.0 | 4 | 800 |

> ⚠️ Already at row 9 we can see a **missing Date** (`NaN`)! Let's investigate further.

---

In [32]:
# ---- GET FULL OVERVIEW USING .info() ----

# .info() shows:
#   - Number of rows and columns
#   - Column names and their data types
#   - Non-null count (how many values are NOT missing)

print("DATASET INFO:")
print("=" * 50)
df.info()

DATASET INFO:
<class 'pandas.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Transaction_ID  107 non-null    str    
 1   Date            107 non-null    str    
 2   Product         106 non-null    str    
 3   Category        107 non-null    str    
 4   Price           107 non-null    float64
 5   Quantity        110 non-null    int64  
 6   Revenue         110 non-null    int64  
dtypes: float64(1), int64(2), str(4)
memory usage: 10.1 KB


**Expected Output:**
```
DATASET INFO:
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Transaction_ID  107 non-null    object     ⬅️ 3 missing!
 1   Date            107 non-null    object     ⬅️ 3 missing! Also stored as text!
 2   Product         106 non-null    object     ⬅️ 4 missing!
 3   Category        107 non-null    object     ⬅️ 3 missing!
 4   Price           107 non-null    float64    ⬅️ 3 missing!
 5   Quantity        110 non-null    int64      ✅
 6   Revenue         110 non-null    int64      ✅
```

**Problems Found:**
- ❌ Multiple columns have missing values
- ❌ `Date` column is stored as `object` (text), not `datetime`
- ❌ `Price` is `float64` instead of `int64` (because NaN forces float)

---

In [33]:
# ---- COMPLETE DATA QUALITY SUMMARY ----

print("📋 DATA QUALITY SUMMARY")
print("=" * 60)

# Missing values
print("\n1. MISSING VALUES PER COLUMN:")
print(df.isnull().sum())
print(f"\n   Total missing values: {df.isnull().sum().sum()}")

# Duplicates
print(f"\n2. DUPLICATE ROWS: {df.duplicated().sum()}")

# Data types
print("\n3. DATA TYPES:")
print(df.dtypes)

# Unique values in text columns
print(f"\n4. UNIQUE PRODUCTS:  {df['Product'].dropna().unique()}")
print(f"   UNIQUE CATEGORIES: {df['Category'].dropna().unique()}")

📋 DATA QUALITY SUMMARY

1. MISSING VALUES PER COLUMN:
Transaction_ID    3
Date              3
Product           4
Category          3
Price             3
Quantity          0
Revenue           0
dtype: int64

   Total missing values: 16

2. DUPLICATE ROWS: 10

3. DATA TYPES:
Transaction_ID        str
Date                  str
Product               str
Category              str
Price             float64
Quantity            int64
Revenue             int64
dtype: object

4. UNIQUE PRODUCTS:  <ArrowStringArray>
['Headphones', 'Smartphone', 'Laptop', 'Smartwatch', 'Tablet']
Length: 5, dtype: str
   UNIQUE CATEGORIES: <ArrowStringArray>
['Accessories', 'Electronics']
Length: 2, dtype: str


**Expected Output:**
```
📋 DATA QUALITY SUMMARY
============================================================

1. MISSING VALUES PER COLUMN:
Transaction_ID    3
Date              3
Product           4
Category          3
Price             3
Quantity          0
Revenue           0

   Total missing values: 16

2. DUPLICATE ROWS: 10

3. DATA TYPES:
Transaction_ID     object
Date               object    ⬅️ Should be datetime!
Product            object
Category           object
Price             float64
Quantity            int64
Revenue             int64

4. UNIQUE PRODUCTS:  ['Headphones', 'Smartphone', 'Laptop', 'Smartwatch', 'Tablet']
   UNIQUE CATEGORIES: ['Accessories', 'Electronics']
```

**Summary of Issues:**
- ❌ **16 missing values** across 5 columns
- ❌ **10 duplicate rows**
- ❌ **Date stored as text** (object), not datetime

Now let's learn how to **fix each of these problems!**

---

### Step 2: Handling Missing Values

Missing values appear as **`NaN`** (Not a Number) or **`None`** in Python. They are one of the most common data quality problems.

**Two Main Strategies:**

| Strategy | Method | When to Use |
|---|---|---|
| **Remove** the row | `dropna()` | When very few rows are missing, and they are not important |
| **Fill** with a value | `fillna()` | When you don't want to lose data — fill with mean, median, mode, or a default value |

---

#### 2.1 Detecting Missing Values

In [34]:
# ---- DETECT MISSING VALUES ----

# .isnull() marks each cell as True (missing) or False (not missing)
# .sum() counts how many True values per column

print("MISSING VALUES COUNT PER COLUMN:")
print("=" * 40)
print(df.isnull().sum())

print(f"\nTOTAL MISSING VALUES: {df.isnull().sum().sum()}")

MISSING VALUES COUNT PER COLUMN:
Transaction_ID    3
Date              3
Product           4
Category          3
Price             3
Quantity          0
Revenue           0
dtype: int64

TOTAL MISSING VALUES: 16


**Expected Output:**
```
MISSING VALUES COUNT PER COLUMN:
========================================
Transaction_ID    3
Date              3
Product           4
Category          3
Price             3
Quantity          0
Revenue           0
dtype: int64

TOTAL MISSING VALUES: 16
```

---

In [35]:
# ---- VIEW THE ACTUAL ROWS WITH MISSING VALUES ----

# .isnull().any(axis=1) checks each ROW — True if ANY column is missing
# df[...] filters to show only those rows

print("ROWS WITH MISSING VALUES:")
missing_rows = df[df.isnull().any(axis=1)]
print(missing_rows)
print(f"\n→ {len(missing_rows)} rows have at least one missing value")

ROWS WITH MISSING VALUES:
    Transaction_ID        Date     Product     Category   Price  Quantity  \
9         TXN-1010         NaN  Smartwatch  Accessories   200.0         4   
13             NaN  2026-01-11  Headphones  Accessories   150.0         5   
32        TXN-1033         NaN  Smartphone  Electronics   600.0         1   
36        TXN-1037  2026-01-25      Laptop  Electronics     NaN         3   
38        TXN-1039         NaN  Smartphone  Electronics   600.0         1   
39        TXN-1040  2026-01-27         NaN  Electronics  1000.0         4   
41        TXN-1042  2026-01-10      Tablet          NaN   400.0         5   
62             NaN  2026-01-18  Headphones  Accessories   150.0         2   
65        TXN-1066  2026-01-28      Tablet          NaN   400.0         2   
66        TXN-1067  2026-01-14  Smartwatch  Accessories     NaN         1   
74             NaN  2026-01-28  Smartwatch  Accessories   200.0         5   
76        TXN-1077  2026-01-28         NaN  Access

In [36]:
# ---- MISSING VALUE SUMMARY TABLE ----

# Calculate count and percentage of missing values per column
# Percentage tells us HOW SERIOUS the problem is

missing_count = df.isnull().sum()                        # Count of missing per column
missing_percent = (missing_count / len(df)) * 100        # Percentage of missing

# Create a nice summary table
missing_summary = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing %': missing_percent.round(2)                # Round to 2 decimal places
})

print("MISSING VALUES — COUNT & PERCENTAGE")
print(missing_summary)

MISSING VALUES — COUNT & PERCENTAGE
                Missing Count  Missing %
Transaction_ID              3       2.73
Date                        3       2.73
Product                     4       3.64
Category                    3       2.73
Price                       3       2.73
Quantity                    0       0.00
Revenue                     0       0.00


**Expected Output:**
```
MISSING VALUES — COUNT & PERCENTAGE
==================================================
                Missing Count  Missing %
Transaction_ID              3       2.73
Date                        3       2.73
Product                     4       3.64
Category                    3       2.73
Price                       3       2.73
Quantity                    0       0.00
Revenue                     0       0.00
```

> All columns have less than 4% missing — this is a low amount, but we still need to handle it!

---

#### 2.3 Strategy 1: Removing Rows with Missing Values — `dropna()`

The `dropna()` function **removes any row that has at least one missing value**.

In [37]:
# ---- STRATEGY 1: DROP ROWS WITH MISSING VALUES ----

# dropna() removes ALL rows that have ANY missing value
# We use a COPY so we don't change the original data yet

df_dropped = df.dropna()  # Returns a NEW DataFrame without missing values

print("BEFORE dropna():")
print(f"  Rows: {len(df)}")

print("\nAFTER dropna():")
print(f"  Rows: {len(df_dropped)}")
print(f"  Rows removed: {len(df) - len(df_dropped)}")
print(f"  Data lost: {((len(df) - len(df_dropped)) / len(df) * 100):.1f}%")

BEFORE dropna():
  Rows: 110

AFTER dropna():
  Rows: 94
  Rows removed: 16
  Data lost: 14.5%


**Expected Output:**
```
BEFORE dropna():
  Rows: 110

AFTER dropna():
  Rows: 94
  Rows removed: 16
  Data lost: 14.5%
```

> ⚠️ **Warning:** We lost 16 rows! That's about 14.5% of our data. This might be too aggressive. Let's learn smarter approaches.

---

#### 2.4 Dropping Rows Missing in a SPECIFIC Column — `dropna(subset=)`

Instead of dropping rows missing in **any** column, we can drop only rows missing in a **specific** column.

In [38]:
# ---- DROP ROWS WHERE 'Transaction_ID' IS MISSING ----

# subset=['Transaction_ID'] → Only drop rows where Transaction_ID is NaN
# We can't fill/guess a Transaction ID — it's a unique identifier
# So dropping is the right choice here

df_dropped_id = df.dropna(subset=['Transaction_ID'])

print("DROP only rows where 'Transaction_ID' is missing:")
print(f"  Before: {len(df)} rows")
print(f"  After:  {len(df_dropped_id)} rows")
print(f"  Removed: {len(df) - len(df_dropped_id)} row(s)")

DROP only rows where 'Transaction_ID' is missing:
  Before: 110 rows
  After:  107 rows
  Removed: 3 row(s)


**Expected Output:**
```
DROP only rows where 'Transaction_ID' is missing:
  Before: 110 rows
  After:  107 rows
  Removed: 3 row(s)
```

> ✅ **Much better!** We only lost 3 rows (where Transaction_ID was missing) instead of 16 rows.

---

#### 2.5 Strategy 2: Filling Missing Values — `fillna()`

Instead of removing rows, we can **fill** missing values with a replacement. This is usually the better approach because we don't lose data.

**Common fill strategies:**

| Strategy | Code | Best For |
|---|---|---|
| Fill with a **specific value** | `fillna(0)` or `fillna('Unknown')` | When you know a sensible default |
| Fill with the **mean** (average) | `fillna(df['col'].mean())` | Numerical columns with no outliers |
| Fill with the **median** (middle value) | `fillna(df['col'].median())` | Numerical columns WITH outliers |
| Fill with the **mode** (most common) | `fillna(df['col'].mode()[0])` | Categorical (text) columns |

In [39]:
# ---- FILLNA WITH A SPECIFIC VALUE ----

# Let's fill missing 'Category' values with 'Unknown'
# This is useful when we don't know the correct value but want to keep the row

df_fill_example = df.copy()  # Make a copy to not change the original

# BEFORE: Check missing values in Category
print("BEFORE fillna():")
print(f"  Missing Category values: {df_fill_example['Category'].isnull().sum()}")

# Show the rows where Category is missing
print("\n  Rows with missing Category:")
print(df_fill_example[df_fill_example['Category'].isnull()][['Transaction_ID', 'Product', 'Category']])

# FILL: Replace NaN in Category with 'Unknown'
df_fill_example['Category'] = df_fill_example['Category'].fillna('Unknown')

# AFTER: Check again
print("\nAFTER fillna('Unknown'):")
print(f"  Missing Category values: {df_fill_example['Category'].isnull().sum()}")


BEFORE fillna():
  Missing Category values: 3

  Rows with missing Category:
   Transaction_ID     Product Category
41       TXN-1042      Tablet      NaN
65       TXN-1066      Tablet      NaN
78       TXN-1079  Headphones      NaN

AFTER fillna('Unknown'):
  Missing Category values: 0


**Expected Output:**
```
BEFORE fillna():
  Missing Category values: 3

  Rows with missing Category:
    Transaction_ID  Product Category
41       TXN-1042   Tablet      NaN
65       TXN-1066   Tablet      NaN
78       TXN-1079  Headphones   NaN

AFTER fillna('Unknown'):
  Missing Category values: 0
```

> ✅ The 3 `NaN` values in Category have been replaced with `'Unknown'`.

---

In [40]:
df["Price"].head(10)


0     150.0
1     600.0
2     600.0
3     150.0
4     150.0
5    1000.0
6     200.0
7     200.0
8     600.0
9     200.0
Name: Price, dtype: float64

In [41]:
# ---- FILLNA WITH MEAN (for numerical columns) ----

# The MEAN is the average value
# Best for numerical columns when there are no extreme outliers

df_fill_mean = df.copy()

# Calculate the mean of Price column (NaN values are ignored automatically)
price_mean = round(df_fill_mean['Price'].mean(),2)
print(f"Mean of Price: {price_mean}")

# BEFORE: Show rows with missing Price
print(f"\nMissing Price values BEFORE: {df_fill_mean['Price'].isnull().sum()}")
print("\nRows with missing Price:")
print(df_fill_mean[df_fill_mean['Price'].isnull()][['Transaction_ID', 'Product', 'Price']])

# Fill missing Price values with the mean
df_fill_mean['Price'] = df_fill_mean['Price'].fillna(price_mean)

# AFTER
print(f"\nMissing Price values AFTER: {df_fill_mean['Price'].isnull().sum()}")

print(df_fill_mean.loc[66,"Price"])

Mean of Price: 487.85

Missing Price values BEFORE: 3

Rows with missing Price:
   Transaction_ID     Product  Price
36       TXN-1037      Laptop    NaN
66       TXN-1067  Smartwatch    NaN
88       TXN-1089      Laptop    NaN

Missing Price values AFTER: 0
487.85


**Expected Output:**
```
Mean of Price: 481.31

Missing Price values BEFORE: 3

Rows with missing Price:
    Transaction_ID     Product  Price
36       TXN-1037      Laptop    NaN
66       TXN-1067  Smartwatch    NaN
88       TXN-1089      Laptop    NaN

Missing Price values AFTER: 0
```

> ✅ All 3 missing Price values have been filled with the average price.

---

In [42]:
# ---- FILLNA WITH MEDIAN (for numerical columns with outliers) ----

# The MEDIAN is the middle value when data is sorted
# Better than mean when there are extreme values (outliers)

df_fill_median = df.copy()

# Calculate the median of Price column
price_median = df_fill_median['Price'].median()
print(f"Median of Price: {price_median}")
print(f"Mean of Price:   {df_fill_median['Price'].mean():.2f}")
print("→ Median is more robust when data has outliers!")

# Fill missing Price values with the median
df_fill_median['Price'] = df_fill_median['Price'].fillna(price_median)

print(f"\nMissing Price values after fillna(median): {df_fill_median['Price'].isnull().sum()}")
print(df_fill_median.loc[66,"Price"])

Median of Price: 400.0
Mean of Price:   487.85
→ Median is more robust when data has outliers!

Missing Price values after fillna(median): 0
400.0


**Expected Output:**
```
Median of Price: 400.0
Mean of Price:   481.31
→ Median is more robust when data has outliers!

Missing Price values after fillna(median): 0
```

---

In [43]:
# ---- FILLNA WITH MODE (for categorical/text columns) ----

# The MODE is the most frequently occurring value
# Best for categorical (text) columns like Product, Category

df_fill_mode = df.copy()

# Calculate the mode (most common value) of Product column
product_mode = df_fill_mode['Product'].mode()[0] # [0] gets the first mode value
print(f"Mode of Product: '{product_mode}'")

# # Show how many times each product appears
print("\nProduct frequency:")
print(df_fill_mode['Product'].value_counts())

# Fill missing Product values with the mode
df_fill_mode['Product'] = df_fill_mode['Product'].fillna(product_mode)

print(f"\nMissing Product values after fillna(mode): {df_fill_mode['Product'].isnull().sum()}")

Mode of Product: 'Laptop'

Product frequency:
Product
Laptop        26
Headphones    24
Tablet        22
Smartwatch    19
Smartphone    15
Name: count, dtype: int64

Missing Product values after fillna(mode): 0


**Expected Output:**
```
Mode of Product: 'Laptop'

Product frequency:
Laptop        27
Headphones    22
Smartphone    21
Tablet        19
Smartwatch    17

Missing Product values after fillna(mode): 0
```

> ✅ The 4 missing Product values were filled with `'Laptop'` (the most common product).

---

#### 📋 Summary: When to Use Which Strategy?

| Situation | Best Strategy | Our Dataset Example |
|---|---|---|
| Unique identifier missing | `dropna(subset=['col'])` | Drop rows where `Transaction_ID` is missing |
| Cannot guess the correct date | `dropna(subset=['col'])` | Drop rows where `Date` is missing |
| Numerical column, no outliers | `fillna(mean)` | Fill missing `Price` with average price |
| Numerical column, has outliers | `fillna(median)` | Fill missing `Price` with median price |
| Categorical (text) column | `fillna(mode)` | Fill missing `Product` with most common product |
| You know the default value | `fillna('value')` | Fill missing `Category` with `'Unknown'` |

---

### Step 3: Removing Duplicate Records

A **duplicate row** is an exact copy of another row — every column value is the same.

**Why are duplicates bad?**
- Revenue gets counted twice → wrong total sales
- Product counts get inflated
- Analysis results become unreliable

---

#### 3.1 Detecting Duplicates

In [44]:
# ---- DETECT DUPLICATE ROWS ----

# .duplicated() marks each row as True (duplicate) or False (unique)
# By default, it keeps the FIRST occurrence and marks later ones as duplicates
# .sum() counts the total number of duplicate rows

print("DUPLICATE CHECK:")
print("=" * 40)
print(f"Total rows: {len(df)}")
print(f"Duplicate rows: {df.duplicated().sum()}")

DUPLICATE CHECK:
Total rows: 110
Duplicate rows: 10


**Expected Output:**
```
DUPLICATE CHECK:
========================================
Total rows: 110
Duplicate rows: 10
```

> That's 10 duplicate rows out of 110 — nearly 10% of our data is duplicated!

---

#### 3.2 Viewing the Duplicate Rows

In [45]:
# ---- VIEW THE DUPLICATE ROWS ----

# df[df.duplicated()] filters and shows ONLY the duplicate rows
# This helps us SEE which rows are duplicated before removing them

print("THESE ARE THE DUPLICATE ROWS:")
print("=" * 80)
duplicates = df[df.duplicated()]
print(duplicates)

print(f"\n→ {len(duplicates)} duplicate row(s) found")

THESE ARE THE DUPLICATE ROWS:
    Transaction_ID        Date     Product     Category   Price  Quantity  \
100       TXN-1084  2026-01-14  Smartphone  Electronics   600.0         4   
101       TXN-1054  2026-01-20      Laptop  Electronics  1000.0         1   
102       TXN-1071  2026-01-26      Tablet  Electronics   400.0         2   
103       TXN-1046  2026-01-15      Laptop  Electronics  1000.0         3   
104       TXN-1045  2026-01-16      Tablet  Electronics   400.0         4   
105       TXN-1040  2026-01-27         NaN  Electronics  1000.0         4   
106       TXN-1023  2026-01-02      Laptop  Electronics  1000.0         1   
107       TXN-1081  2026-01-08  Headphones  Accessories   150.0         3   
108       TXN-1011  2026-01-19  Smartphone  Electronics   600.0         2   
109       TXN-1001  2026-01-07  Headphones  Accessories   150.0         2   

     Revenue  
100     2400  
101     1000  
102      800  
103     3000  
104     1600  
105     4000  
106     1000  
10

**Expected Output:**
```
THESE ARE THE DUPLICATE ROWS:
================================================================================
    Transaction_ID        Date     Product     Category   Price  Quantity  Revenue
100       TXN-1084  2026-01-14  Smartphone  Electronics   600.0         4     2400
101       TXN-1054  2026-01-20      Laptop  Electronics  1000.0         1     1000
102       TXN-1071  2026-01-26      Tablet  Electronics   400.0         2      800
103       TXN-1046  2026-01-15      Laptop  Electronics  1000.0         3     3000
104       TXN-1045  2026-01-16      Tablet  Electronics   400.0         4     1600
105       TXN-1040  2026-01-27         NaN  Electronics  1000.0         4     4000
106       TXN-1023  2026-01-02      Laptop  Electronics  1000.0         1     1000
107       TXN-1081  2026-01-08  Headphones  Accessories   150.0         3      450
108       TXN-1011  2026-01-19  Smartphone  Electronics   600.0         2     1200
109       TXN-1001  2026-01-07  Headphones  Accessories   150.0         2      300

→ 10 duplicate row(s) found
```

> Notice: Rows 100–109 are duplicates of earlier rows (e.g., row 109 is a copy of row 0).

---

#### 3.3 Removing Duplicates — `drop_duplicates()`

In [46]:
# ---- REMOVE DUPLICATE ROWS ----

# drop_duplicates() removes duplicate rows and keeps the FIRST occurrence
# We use a COPY to demonstrate without changing the original

df_no_dupes = df.drop_duplicates()

print("BEFORE drop_duplicates():")
print(f"  Rows: {len(df)}")

print("\nAFTER drop_duplicates():")
print(f"  Rows: {len(df_no_dupes)}")
print(f"  Duplicates removed: {len(df) - len(df_no_dupes)}")

# Verify: no duplicates remain
print(f"  Remaining duplicates: {df_no_dupes.duplicated().sum()}")

BEFORE drop_duplicates():
  Rows: 110

AFTER drop_duplicates():
  Rows: 100
  Duplicates removed: 10
  Remaining duplicates: 0


**Expected Output:**
```
BEFORE drop_duplicates():
  Rows: 110

AFTER drop_duplicates():
  Rows: 100
  Duplicates removed: 10
  Remaining duplicates: 0
```

> ✅ All 10 duplicate rows removed! We went from 110 to 100 rows.

---

In [47]:
# ---- USING inplace=True ----

# inplace=True modifies the DataFrame DIRECTLY (no need to create a new variable)
# Without inplace=True, you must save the result: df = df.drop_duplicates()

df_example = df.copy()  # Work on a copy

print(f"Before: {len(df_example)} rows")

# Method 1: Without inplace (save the result)
df_example = df_example.drop_duplicates()

# Method 2: With inplace=True (modifies directly)
df_example.drop_duplicates(inplace=True)

print(f"After:  {len(df_example)} rows")
print("\n💡 Both methods do the same thing!")

Before: 110 rows
After:  100 rows

💡 Both methods do the same thing!


**Expected Output:**
```
Before: 110 rows
After:  100 rows

💡 Both methods do the same thing!
```

> 💡 **Tip:** Both methods do the same thing.
> - `df = df.drop_duplicates()` — saves result to variable
> - `df.drop_duplicates(inplace=True)` — modifies directly

---

### Step 4: Fixing Data Types

Sometimes data is stored in the **wrong type**. The most common issue is **dates stored as text** (strings).

**Why does it matter?**

| Stored As | What You CAN'T Do |
|---|---|
| Date as text (`"2026-01-15"`) | Cannot sort by date, cannot calculate days between dates |
| Numbers as text (`"150"`) | Cannot calculate sum, average, or do math |

---

#### 4.1 Check Current Data Types

In [48]:
# ---- CHECK DATA TYPES ----

# .dtypes shows the data type of each column
# Common types:
#   int64    → whole numbers (e.g., 150, 2)
#   float64  → decimal numbers (e.g., 3.14, 25.0)
#   object   → text/strings (e.g., 'Laptop', '2026-01-15')
#   datetime → proper date/time values

print("DATA TYPES IN OUR SALES DATASET:")
print("=" * 40)
print(df.dtypes)

print("\n  Notice: 'Date' is stored as 'object' (text), not as a proper date!")
print(f" Sample Date value: '{df['Date'].iloc[0]}' — looks like a date, but is actually text")

DATA TYPES IN OUR SALES DATASET:
Transaction_ID        str
Date                  str
Product               str
Category              str
Price             float64
Quantity            int64
Revenue             int64
dtype: object

  Notice: 'Date' is stored as 'object' (text), not as a proper date!
 Sample Date value: '2026-01-07' — looks like a date, but is actually text


**Expected Output:**
```
DATA TYPES IN OUR SALES DATASET:
========================================
Transaction_ID     object
Date               object    ⬅️ Should be datetime!
Product            object
Category           object
Price             float64
Quantity            int64
Revenue             int64

⚠️  Notice: 'Date' is stored as 'object' (text), not as a proper date!
    Sample Date value: '2026-01-07' — looks like a date, but is actually text
```

---

#### 4.2 Convert Text to Date — `pd.to_datetime()`

In [49]:
# ---- CONVERT STRING TO DATETIME ----

# pd.to_datetime() converts text dates to proper datetime format
# This allows us to sort by date, extract month/year, calculate date differences

df_typed = df.copy()

# BEFORE conversion
print("BEFORE conversion:")
print(f"  Type of Date column: {df_typed['Date'].dtype}")
print(f"  Sample value: {df_typed['Date'].iloc[0]} (type: {type(df_typed['Date'].iloc[0])})")

# CONVERT: String → Datetime
df_typed['Date'] = pd.to_datetime(df_typed['Date'],format="mixed")

# AFTER conversion
print("\nAFTER conversion:")
print(f"  Type of Date column: {df_typed['Date'].dtype}")
print(f"  Sample value: {df_typed['Date'].iloc[0]} (type: {type(df_typed['Date'].iloc[0])})")

BEFORE conversion:
  Type of Date column: str
  Sample value: 2026-01-07 (type: <class 'str'>)

AFTER conversion:
  Type of Date column: datetime64[us]
  Sample value: 2026-01-07 00:00:00 (type: <class 'pandas.Timestamp'>)


**Expected Output:**
```
BEFORE conversion:
  Type of Date column: object
  Sample value: 2026-01-07 (type: <class 'str'>)

AFTER conversion:
  Type of Date column: datetime64[ns]
  Sample value: 2026-01-07 00:00:00 (type: <class 'pandas._libs.tslibs.timestamps.Timestamp'>)
```

> ✅ Now `Date` is a proper datetime! We can sort by date, extract month/year, and more.

---

In [50]:
# ---- WHAT CAN YOU DO WITH DATETIME COLUMNS? ----

# Once converted to datetime, you can extract parts of the date:

# Drop NaN dates first for clean demo
df_date_demo = df_typed.dropna(subset=['Date'])

print(df_date_demo['Date'].head())

# Extract the month name
print("Month names (first 5):\n", df_date_demo['Date'].dt.month_name().head())

# Extract the year
print("Years (first 5):", df_date_demo['Date'].dt.year.head())

# Extract the day of the week
print("Day names (first 5):", df_date_demo['Date'].dt.day_name().head())

# Extract just the day number
print("Day numbers (first 5):", df_date_demo['Date'].dt.day.head())

0   2026-01-07
1   2026-01-20
2   2026-01-29
3   2026-01-15
4   2026-01-11
Name: Date, dtype: datetime64[us]
Month names (first 5):
 0    January
1    January
2    January
3    January
4    January
Name: Date, dtype: str
Years (first 5): 0    2026
1    2026
2    2026
3    2026
4    2026
Name: Date, dtype: int32
Day names (first 5): 0    Wednesday
1      Tuesday
2     Thursday
3     Thursday
4       Sunday
Name: Date, dtype: str
Day numbers (first 5): 0     7
1    20
2    29
3    15
4    11
Name: Date, dtype: int32


**Expected Output:**
```
Month names (first 5): ['January', 'January', 'January', 'January', 'January']
Years (first 5): [2026, 2026, 2026, 2026, 2026]
Day names (first 5): ['Wednesday', 'Tuesday', 'Thursday', 'Thursday', 'Sunday']
Day numbers (first 5): [7, 20, 29, 15, 11]
```

> 💡 These operations are **impossible** when dates are stored as text strings!

---

### Step 5: Cleaning Text Columns

Text data often has these problems:

| Problem | Example | Why It's Bad |
|---|---|---|
| Extra spaces | `"  Laptop  "` | `"Laptop"` ≠ `"  Laptop  "` — counted as different products |
| Inconsistent case | `"electronics"` vs `"Electronics"` | Treated as two different categories |
| Typos | `"Elektronics"` | Won't match `"Electronics"` in filters |

**Key Methods:**

| Method | What It Does | Example |
|---|---|---|
| `.str.strip()` | Removes leading/trailing spaces | `"  Laptop  "` → `"Laptop"` |
| `.str.lower()` | Converts all text to lowercase | `"Electronics"` → `"electronics"` |
| `.str.upper()` | Converts all text to UPPERCASE | `"Electronics"` → `"ELECTRONICS"` |
| `.str.title()` | Converts to Title Case | `"electronics"` → `"Electronics"` |
| `.str.replace()` | Replaces specific text | `"Elektronics"` → `"Electronics"` |

---

#### 5.1 Applying Text Cleaning to Our Sales Data

In [51]:
# ---- CHECK TEXT COLUMNS BEFORE CLEANING ----

# Even if data looks clean, ALWAYS apply text cleaning as a precaution
# Hidden spaces or case issues are invisible but cause real problems

print("UNIQUE VALUES BEFORE TEXT CLEANING:\n")
print(f"Products:   {df['Product'].dropna().unique().tolist()}")
print(f"Categories: {df['Category'].dropna().unique().tolist()}")

# Let's check for hidden spaces by showing the length of each unique product
print("\nChecking for hidden spaces (length of each unique product):")
for product in df['Product'].dropna().unique():
    print(f"  '{product}' → length: {len(product)}")

UNIQUE VALUES BEFORE TEXT CLEANING:

Products:   ['Headphones', 'Smartphone', 'Laptop', 'Smartwatch', 'Tablet']
Categories: ['Accessories', 'Electronics']

Checking for hidden spaces (length of each unique product):
  'Headphones' → length: 10
  'Smartphone' → length: 10
  'Laptop' → length: 6
  'Smartwatch' → length: 10
  'Tablet' → length: 6


**Expected Output:**
```
UNIQUE VALUES BEFORE TEXT CLEANING:
==================================================
Products:   ['Headphones', 'Smartphone', 'Laptop', 'Smartwatch', 'Tablet']
Categories: ['Accessories', 'Electronics']

Checking for hidden spaces (length of each unique product):
  'Headphones' → length: 10
  'Smartphone' → length: 10
  'Laptop' → length: 6
  'Smartwatch' → length: 10
  'Tablet' → length: 6
```

---

In [52]:
# ---- APPLY TEXT CLEANING AS A BEST PRACTICE ----

# ALWAYS apply strip() + title() on text columns — even if data looks clean
# This protects against hidden problems and ensures consistency

df_text_clean = df.copy()

# Clean Product column: remove spaces + apply Title Case
df_text_clean['Product'] = df_text_clean['Product'].str.strip().str.title()

# Clean Category column: remove spaces + apply Title Case
df_text_clean['Category'] = df_text_clean['Category'].str.strip().str.title()

# Clean Transaction_ID column: remove extra spaces
df_text_clean['Transaction_ID'] = df_text_clean['Transaction_ID'].str.strip()

print("✅ TEXT CLEANING APPLIED")
print(f"Unique Products after cleaning:   {df_text_clean['Product'].dropna().unique().tolist()}")
print(f"Unique Categories after cleaning: {df_text_clean['Category'].dropna().unique().tolist()}")

✅ TEXT CLEANING APPLIED
Unique Products after cleaning:   ['Headphones', 'Smartphone', 'Laptop', 'Smartwatch', 'Tablet']
Unique Categories after cleaning: ['Accessories', 'Electronics']


**Expected Output:**
```
✅ TEXT CLEANING APPLIED
==================================================
Unique Products after cleaning:   ['Headphones', 'Smartphone', 'Laptop', 'Smartwatch', 'Tablet']
Unique Categories after cleaning: ['Accessories', 'Electronics']
```

> ✅ Text columns are clean and consistent!

> 💡 **Best Practice:** Always apply `.str.strip().str.title()` on text columns — even if the data looks clean. It costs nothing and prevents hidden bugs!

---

In [53]:
# ---- DEMONSTRATION: WHAT HAPPENS IF TEXT IS NOT CLEANED ----

# Let's see why text cleaning matters using a quick example
# Imagine our Product column had inconsistent values:

messy_products = pd.Series(['  Laptop  ', 'laptop', 'LAPTOP', 'Laptop', ' Laptop'])

print("WITHOUT cleaning — value_counts():")
print(messy_products.value_counts())
print(f"→ Python sees {messy_products.nunique()} different products!\n")

# # Now clean them
clean_products = messy_products.str.strip().str.title()

print("WITH cleaning — value_counts():")
print(clean_products.value_counts())
print(f"→ Now Python correctly sees {clean_products.nunique()} product!")

WITHOUT cleaning — value_counts():
  Laptop      1
laptop        1
LAPTOP        1
Laptop        1
 Laptop       1
Name: count, dtype: int64
→ Python sees 5 different products!

WITH cleaning — value_counts():
Laptop    5
Name: count, dtype: int64
→ Now Python correctly sees 1 product!


**Expected Output:**
```
WITHOUT cleaning — value_counts():
  Laptop      1
laptop        1
LAPTOP        1
Laptop        1
 Laptop       1
→ Python sees 5 different products!

WITH cleaning — value_counts():
Laptop    5
→ Now Python correctly sees 1 product!
```

> ⚠️ Without cleaning, the same product "Laptop" would be counted as **5 different products!**

---

### Step 6: Outlier Detection and Handling

**Outliers** are data points that are significantly different from the rest of the data. They can distort statistical analyses and machine learning models.

**How to handle them?**
1. **Detection:** We typically use the **IQR (Interquartile Range)** method or visualization (like boxplots) to find them.
2. **Handling:** We can either **remove** them or **cap** them (replace extreme values with a maximum limit).

---

#### 6.1 Detecting Outliers (IQR Method)

In [54]:
# ---- DETECT OUTLIERS USING IQR ----

# Let's check for outliers in the 'Price' column

# 1. Calculate Q1 (25th percentile) and Q3 (75th percentile)
Q1 = df['Price'].quantile(0.25)
Q3 = df['Price'].quantile(0.75)
IQR = Q3 - Q1
print(Q1)
print(Q3)
print(IQR)
# 2. Calculate the lower and upper bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("OUTLIER BOUNDARIES:")
print(f"  Lower Bound: {lower_bound}")
print(f"  Upper Bound: {upper_bound}")

# 3. Identify the outliers
outliers = df[(df['Price'] < lower_bound) | (df['Price'] > upper_bound)]
print(f"\n→ Found {len(outliers)} outliers in Price")
if len(outliers) > 0:
    print("\nSample of outliers:")
    print(outliers[['Transaction_ID', 'Product', 'Price']].head())

200.0
800.0
600.0
OUTLIER BOUNDARIES:
  Lower Bound: -700.0
  Upper Bound: 1700.0

→ Found 0 outliers in Price


**Expected Output:**
```
OUTLIER BOUNDARIES:
  Lower Bound: -475.0
  Upper Bound: 1125.0

→ Found X outliers in Price
```

---

#### 6.2 Handling Outliers (Capping/Clipping)

In [55]:
# ---- HANDLE OUTLIERS BY CAPPING ----

# Capping (or clipping) replaces values outside the bounds with the bound values.
# This is often better than dropping rows, as we keep the data.

df_no_outliers = df.copy()

print("BEFORE CAPPING:")
print(f"  Max Price: {df_no_outliers['Price'].max()}")

# Apply the .clip() function
df_no_outliers['Price'] = df_no_outliers['Price'].clip(lower=lower_bound, upper=upper_bound)

print("\nAFTER CAPPING:")
print(f"  Max Price: {df_no_outliers['Price'].max()}")

# Verify no outliers remain
remaining_outliers = df_no_outliers[(df_no_outliers['Price'] < lower_bound) | (df_no_outliers['Price'] > upper_bound)]
print(f"\n✅ Remaining outliers: {len(remaining_outliers)}")

BEFORE CAPPING:
  Max Price: 1000.0

AFTER CAPPING:
  Max Price: 1000.0

✅ Remaining outliers: 0


**Expected Output:**
```
BEFORE CAPPING:
  Max Price: 1000.0

AFTER CAPPING:
  Max Price: 1000.0

✅ Remaining outliers: 0
```

---

---

## 🏗️ Project Application — Complete Cleaning Pipeline

Now let's put it all together! We'll clean the **entire `sales_data_messy.xlsx` dataset** from start to finish using a proper pipeline.

---

### Step-by-Step: Full Data Cleaning Pipeline

In [58]:
# ======================================================
# COMPLETE DATA CLEANING PIPELINE
# ======================================================

# ---- STEP 0: LOAD THE RAW MESSY DATA ----
df = pd.read_excel('DataSet_used\\sales_data_messy.xlsx')

print("📊 STARTING THE CLEANING PIPELINE")
print("=" * 60)
print(f"   Rows:           {len(df)}")
print(f"   Missing values: {df.isnull().sum().sum()}")
print(f"   Duplicates:     {df.duplicated().sum()}")
print(f"   Date type:      {df['Date'].dtype}")
print("=" * 60)

📊 STARTING THE CLEANING PIPELINE
   Rows:           110
   Missing values: 16
   Duplicates:     10
   Date type:      str


**Expected Output:**
```
📊 STARTING THE CLEANING PIPELINE
============================================================
   Rows:           110
   Missing values: 16
   Duplicates:     10
   Date type:      object
============================================================
```

---

In [ ]:
# ---- STEP 1: CLEAN TEXT COLUMNS ----
# Do this FIRST so duplicates with text differences are caught later

df['Product'] = df['Product'].str.strip().str.title()
df['Category'] = df['Category'].str.strip().str.title()
df['Transaction_ID'] = df['Transaction_ID'].str.strip()

print("✅ Step 1: Text columns cleaned (strip + title case)")
print(f"   Unique Products:   {sorted(df['Product'].dropna().unique().tolist())}")
print(f"   Unique Categories: {sorted(df['Category'].dropna().unique().tolist())}")

**Expected Output:**
```
✅ Step 1: Text columns cleaned (strip + title case)
   Unique Products:   ['Headphones', 'Laptop', 'Smartphone', 'Smartwatch', 'Tablet']
   Unique Categories: ['Accessories', 'Electronics']
```

---

In [ ]:
# ---- STEP 2: HANDLE MISSING VALUES ----

# Strategy per column:
#   Transaction_ID → DROP (can't guess a unique ID)
#   Date           → DROP (can't guess a transaction date)
#   Product        → FILL with mode (most common product)
#   Category       → FILL with mode (most common category)
#   Price          → FILL with median (numerical, may have outliers)

print("\nMissing values BEFORE handling:")
print(df.isnull().sum())

# Drop rows where Transaction_ID is missing
rows_before = len(df)
df = df.dropna(subset=['Transaction_ID'])
print(f"\n✅ Dropped {rows_before - len(df)} rows with missing Transaction_ID")

# Drop rows where Date is missing
rows_before = len(df)
df = df.dropna(subset=['Date'])
print(f"✅ Dropped {rows_before - len(df)} rows with missing Date")

# Fill missing Product with mode
product_mode = df['Product'].mode()[0]
df['Product'] = df['Product'].fillna(product_mode)
print(f"✅ Filled missing Product with mode: '{product_mode}'")

# Fill missing Category with mode
category_mode = df['Category'].mode()[0]
df['Category'] = df['Category'].fillna(category_mode)
print(f"✅ Filled missing Category with mode: '{category_mode}'")

# Fill missing Price with median
price_median = df['Price'].median()
df['Price'] = df['Price'].fillna(price_median)
print(f"✅ Filled missing Price with median: {price_median}")

print("\nMissing values AFTER handling:")
print(df.isnull().sum())

**Expected Output:**
```
Missing values BEFORE handling:
Transaction_ID    3
Date              3
Product           4
Category          3
Price             3
Quantity          0
Revenue           0

✅ Dropped 3 rows with missing Transaction_ID
✅ Dropped 3 rows with missing Date
✅ Filled missing Product with mode: 'Laptop'
✅ Filled missing Category with mode: 'Electronics'
✅ Filled missing Price with median: 400.0

Missing values AFTER handling:
Transaction_ID    0
Date              0
Product           0
Category          0
Price             0
Quantity          0
Revenue           0
```

> ✅ Zero missing values! All handled.

---

In [ ]:
# ---- STEP 3: REMOVE DUPLICATES ----

rows_before = len(df)
print(f"Rows BEFORE removing duplicates: {rows_before}")
print(f"Duplicate rows found: {df.duplicated().sum()}")

# Remove duplicates, keep the first occurrence
df.drop_duplicates(inplace=True)

print(f"\nRows AFTER removing duplicates: {len(df)}")
print(f"Duplicates removed: {rows_before - len(df)}")
print(f"Remaining duplicates: {df.duplicated().sum()}")
print("\n✅ Duplicates removed successfully!")

**Expected Output:**
```
Rows BEFORE removing duplicates: 104
Duplicate rows found: 10

Rows AFTER removing duplicates: 94
Duplicates removed: 10
Remaining duplicates: 0

✅ Duplicates removed successfully!
```

> ✅ Note: We had 110 rows initially, dropped 6 (missing ID/Date), then removed 10 duplicates = 94 clean rows.

---

In [ ]:
# ---- STEP 4: FIX DATA TYPES ----

# Convert Date from string to datetime
print("Data type of Date BEFORE:", df['Date'].dtype)

df['Date'] = pd.to_datetime(df['Date'])

print("Data type of Date AFTER: ", df['Date'].dtype)
print("\n✅ Date column converted to datetime!")

**Expected Output:**
```
Data type of Date BEFORE: object
Data type of Date AFTER:  datetime64[ns]

✅ Date column converted to datetime!
```

---

In [ ]:
# ---- STEP 5: FINAL VERIFICATION ----

print("🔍 FINAL VERIFICATION — DATA CLEANING REPORT")
print("=" * 60)

# 1. Dataset Info
print("\n📊 1. DATASET OVERVIEW:")
df.info()

# 2. Missing Values
print("\n📊 2. MISSING VALUES:")
print(df.isnull().sum())

# 3. Duplicates
print(f"\n📊 3. DUPLICATE ROWS: {df.duplicated().sum()}")

# 4. Data Types
print("\n📊 4. DATA TYPES:")
print(df.dtypes)

# 5. Unique values in text columns
print(f"\n📊 5. UNIQUE PRODUCTS:   {sorted(df['Product'].unique().tolist())}")
print(f"   UNIQUE CATEGORIES: {sorted(df['Category'].unique().tolist())}")

print("\n" + "=" * 60)
print("✅ DATA CLEANING COMPLETE — DATASET IS READY FOR ANALYSIS!")

**Expected Output:**
```
🔍 FINAL VERIFICATION — DATA CLEANING REPORT
============================================================

📊 2. MISSING VALUES:
Transaction_ID    0
Date              0
Product           0
Category          0
Price             0
Quantity          0
Revenue           0

📊 3. DUPLICATE ROWS: 0

📊 4. DATA TYPES:
Transaction_ID            object
Date              datetime64[ns]   ✅
Product                   object
Category                  object
Price                    float64
Quantity                   int64
Revenue                    int64

📊 5. UNIQUE PRODUCTS:   ['Headphones', 'Laptop', 'Smartphone', 'Smartwatch', 'Tablet']
   UNIQUE CATEGORIES: ['Accessories', 'Electronics']

============================================================
✅ DATA CLEANING COMPLETE — DATASET IS READY FOR ANALYSIS!
```

---

In [ ]:
# ---- BEFORE vs AFTER COMPARISON ----

print("📊 BEFORE vs AFTER CLEANING")
print("=" * 55)

comparison = pd.DataFrame({
    'Metric': ['Total Rows', 'Missing Values', 'Duplicate Rows',
               'Date Type', 'Unique Products', 'Unique Categories'],
    'Before Cleaning': ['110', '16', '10', 'object (text)', '5', '2'],
    'After Cleaning': [str(len(df)),
                       str(df.isnull().sum().sum()),
                       str(df.duplicated().sum()),
                       str(df['Date'].dtype),
                       str(df['Product'].nunique()),
                       str(df['Category'].nunique())]
})

print(comparison.to_string(index=False))

**Expected Output:**

| Metric | Before Cleaning | After Cleaning |
|---|---|---|
| Total Rows | 110 | 94 |
| Missing Values | 16 | 0 |
| Duplicate Rows | 10 | 0 |
| Date Type | object (text) | datetime64[ns] |
| Unique Products | 5 | 5 |
| Unique Categories | 2 | 2 |

> ✅ Our dataset went from **110 messy rows** to **94 clean rows** — ready for analysis!

---

In [ ]:
# ---- VIEW THE FINAL CLEAN DATA ----

print("FIRST 10 ROWS OF CLEANED DATA:")
df.head(10)

---

## ⚠️ Common Mistakes

Here are the most common beginner mistakes and how to fix them.

---

### ❌ Mistake 1: Forgetting to Save the Result

In [ ]:
# ---- MISTAKE 1: FORGETTING TO SAVE THE RESULT ----

# Reload the messy data for this demo
df_test = pd.read_excel('sales_data_messy.xlsx')

# ❌ WRONG: This does NOT change df_test!
df_test.drop_duplicates()  # This returns a new DataFrame, but we don't save it!
print(f"❌ WRONG — Rows after 'cleaning': {len(df_test)}")  # Still has duplicates!

# ✅ FIX Option 1: Save the result back to the variable
df_test = pd.read_excel('sales_data_messy.xlsx')
df_test = df_test.drop_duplicates()  # Save the result!
print(f"✅ FIX 1 — Rows after cleaning: {len(df_test)}")

# ✅ FIX Option 2: Use inplace=True
df_test2 = pd.read_excel('sales_data_messy.xlsx')
df_test2.drop_duplicates(inplace=True)  # Modifies directly!
print(f"✅ FIX 2 — Rows after cleaning: {len(df_test2)}")

**Expected Output:**
```
❌ WRONG — Rows after 'cleaning': 110
✅ FIX 1 — Rows after cleaning: 100
✅ FIX 2 — Rows after cleaning: 100
```

> ⚠️ Always either: `df = df.drop_duplicates()` OR `df.drop_duplicates(inplace=True)`

---

### ❌ Mistake 2: Using `dropna()` Without Thinking

In [ ]:
# ---- MISTAKE 2: USING dropna() TOO AGGRESSIVELY ----

df_test3 = pd.read_excel('sales_data_messy.xlsx')

# ❌ WRONG: Dropping ALL rows with ANY missing value — loses too much data!
df_wrong = df_test3.dropna()
print(f"❌ WRONG — dropna() removed {len(df_test3) - len(df_wrong)} out of {len(df_test3)} rows!")
print(f"   Only {len(df_wrong)} rows remaining — we lost {((len(df_test3) - len(df_wrong)) / len(df_test3) * 100):.0f}% of data!")

# ✅ FIX: Use dropna(subset=) for IDs and dates, and fillna() for others
df_smart = df_test3.copy()
df_smart = df_smart.dropna(subset=['Transaction_ID', 'Date'])  # Only drop critical missing
df_smart['Product'] = df_smart['Product'].fillna(df_smart['Product'].mode()[0])   # Fill Product
df_smart['Category'] = df_smart['Category'].fillna(df_smart['Category'].mode()[0]) # Fill Category
df_smart['Price'] = df_smart['Price'].fillna(df_smart['Price'].median())           # Fill Price
print(f"\n✅ FIX — Smart cleaning: {len(df_smart)} rows remaining")
print(f"   Missing values: {df_smart.isnull().sum().sum()}")

**Expected Output:**
```
❌ WRONG — dropna() removed 16 out of 110 rows!
   Only 94 rows remaining — we lost 15% of data!

✅ FIX — Smart cleaning: 104 rows remaining
   Missing values: 0
```

> ⚠️ Think carefully about WHICH rows to drop and WHICH to fill! Smart cleaning saved 10 extra rows.

---

### ❌ Mistake 3: Removing Duplicates BEFORE Cleaning Text

In [ ]:
# ---- MISTAKE 3: WRONG ORDER OF OPERATIONS ----

# Imagine our Product column had text issues like '  Laptop  ' and 'Laptop'
# If we remove duplicates FIRST, they won't be detected as duplicates!

# Let's demonstrate with a small example:
demo = pd.DataFrame({
    'Product': ['  Laptop  ', 'Laptop', 'Tablet', '  Laptop  '],
    'Price': [1000, 1000, 400, 1000]
})

# ❌ WRONG: Remove duplicates FIRST, then clean text
demo_wrong = demo.drop_duplicates()
demo_wrong['Product'] = demo_wrong['Product'].str.strip()
print(f"❌ WRONG ORDER — Rows: {len(demo_wrong)}, Duplicates left: {demo_wrong.duplicated().sum()}")

# ✅ CORRECT: Clean text FIRST, then remove duplicates
demo_right = demo.copy()
demo_right['Product'] = demo_right['Product'].str.strip()  # Clean text FIRST
demo_right = demo_right.drop_duplicates()                   # THEN remove duplicates
print(f"✅ RIGHT ORDER — Rows: {len(demo_right)}, Duplicates left: {demo_right.duplicated().sum()}")

**Expected Output:**
```
❌ WRONG ORDER — Rows: 3, Duplicates left: 1
✅ RIGHT ORDER — Rows: 2, Duplicates left: 0
```

> ⚠️ **Remember the correct order:**
> 1. Clean text (strip + title) ← **FIRST**
> 2. Handle missing values
> 3. Remove duplicates ← **AFTER text is clean**
> 4. Fix data types

---

### ❌ Mistake 4: Wrong Syntax for `fillna()` with Mode

In [ ]:
# ---- MISTAKE 4: WRONG MODE SYNTAX ----

df_test5 = pd.read_excel('sales_data_messy.xlsx')

# ❌ WRONG: mode() returns a Series, not a single value!
# df_test5['Product'].fillna(df_test5['Product'].mode())  # This won't work as expected!
print("❌ WRONG: df['Product'].mode() returns:")
print(df_test5['Product'].mode())  # Returns a Series with index
print("   This is a Series, not a single value!\n")

# ✅ FIX: Use mode()[0] to get the FIRST (most common) value
print("✅ FIX: df['Product'].mode()[0] returns:")
print(df_test5['Product'].mode()[0])  # Returns just the value
print("   This is a single value — perfect for fillna()!")

**Expected Output:**
```
❌ WRONG: df['Product'].mode() returns:
0    Laptop
   This is a Series, not a single value!

✅ FIX: df['Product'].mode()[0] returns:
Laptop
   This is a single value — perfect for fillna()!
```

> ⚠️ Always use `.mode()[0]` — the `[0]` extracts the first (most frequent) value.

---

## 📝 Practice Tasks

Try these tasks on your own using the `sales_data_messy.xlsx` dataset. Each task practices a specific cleaning skill.

---

**Task 1: Load and Assess the Messy Data**

Load `sales_data_messy.xlsx` and print the shape, data types, missing value counts, and duplicate count.

---

**Task 2: Create a Missing Value Summary**

Create a DataFrame that shows both the **count** and **percentage** of missing values for each column:
```python
missing_count = df.isnull().sum()
missing_percent = (missing_count / len(df)) * 100
```

---

**Task 3: View All Rows with Missing Values**

Display all rows that have at least one missing value. How many such rows are there?

---

**Task 4: Practice `dropna(subset=)`**

Drop only rows where `Transaction_ID` is missing. How many rows were removed? How many remain?

---

**Task 5: Practice `fillna()` with Median**

Fill the missing `Price` values with the **median** price. What is the median price?

---

**Task 6: Practice `fillna()` with Mode**

Fill the missing `Product` values with the **mode** (most common product). What is the most common product?

---

**Task 7: View and Remove Duplicates**

View all duplicate rows using `df[df.duplicated()]`. Then remove them using `df.drop_duplicates(inplace=True)`. How many were removed?

---

**Task 8: Convert Date Column**

Convert the `Date` column to datetime. Then extract the **day names** for all rows.

---

**Task 9: Apply Text Cleaning**

Apply `.str.strip().str.title()` to the `Product` and `Category` columns. Verify by printing unique values before and after.

---

**Task 10: Complete Cleaning Pipeline**

Write a complete cleaning pipeline that:
1. Loads `sales_data_messy.xlsx`
2. Cleans text columns (strip + title)
3. Handles missing values (drop IDs/Dates, fill others)
4. Removes duplicates
5. Converts Date to datetime
6. Prints a before/after comparison

---

## 📋 Assignment

Complete the following tasks **after class** using the `sales_data_messy.xlsx` dataset. Submit your notebook with all code and output.

---

### 1. Handle Missing Values

- Check missing values using: `df.isnull().sum()`
- If missing values exist, use `fillna()` or `dropna()`.

**Questions:**
- Which columns contain missing values?
- How did you handle them?
- Why is handling missing values important?

---

### 2. Remove Duplicate Records

- Check duplicate rows using: `df.duplicated().sum()`
- Remove duplicates using: `df.drop_duplicates(inplace=True)`

**Questions:**
- How many duplicate rows were found?
- How many rows remain after cleaning?

---

### 3. Check Data Types

- Inspect data types using: `df.dtypes`
- Convert date columns using `pd.to_datetime()`.

**Questions:**
- Which columns required conversion?
- Why should dates be stored as datetime?

---

### 4. Clean Text Columns

- Remove extra spaces using `.str.strip()`
- Apply cleaning to important text columns if needed.

**Questions:**
- Why can extra spaces create problems during analysis?

---

### 5. Verify the Cleaned Dataset

- Run `df.info()`
- Run `df.isnull().sum()`
- Run `df.duplicated().sum()`
- Confirm that missing values, duplicates, and data types have been handled correctly.

---

### Deliverables

Create a **Data Cleaning Report** containing:

1. **Missing Value Treatment** — What was missing and how you handled it
2. **Duplicate Removal Summary** — How many duplicates found and removed
3. **Data Type Corrections** — Which columns were converted and why
4. **Text Cleaning Summary** — What text issues were found and fixed
5. **Final Conclusion** (3–5 observations about the cleaned dataset)

---

## 🔑 Key Takeaways

| # | Takeaway |
|---|---|
| 1 | **Data Cleaning** is the process of fixing missing values, duplicates, wrong types, and text issues |
| 2 | Use **`dropna()`** to remove rows with missing values — but be careful not to lose too much data |
| 3 | Use **`dropna(subset=['col'])`** to drop rows missing only in specific critical columns (like IDs or dates) |
| 4 | Use **`fillna()`** to fill missing values with mean (numbers), median (numbers with outliers), or mode (text) |
| 5 | Use **`drop_duplicates()`** to remove duplicate rows — use `inplace=True` to modify directly |
| 6 | Use **`pd.to_datetime()`** to convert date strings to proper datetime format |
| 7 | Use **`.str.strip()`** to remove extra spaces and **`.str.title()`** to fix case |
| 8 | **Always clean text BEFORE removing duplicates** — otherwise duplicates with different formatting won't be caught |
| 9 | **Always verify** after cleaning: check `isnull().sum()`, `duplicated().sum()`, and `dtypes` |
| 10 | Remember to **save your result**: `df = df.dropna()` or use `inplace=True` |

---

### 🧹 Quick Reference Cheat Sheet

```python
# ---- MISSING VALUES ----
df.isnull().sum()                           # Count missing values
df.dropna()                                 # Drop all rows with any NaN
df.dropna(subset=['col'])                   # Drop rows where specific column is NaN
df['col'].fillna(value)                     # Fill NaN with a specific value
df['col'].fillna(df['col'].mean())          # Fill with mean
df['col'].fillna(df['col'].median())        # Fill with median
df['col'].fillna(df['col'].mode()[0])       # Fill with mode

# ---- DUPLICATES ----
df.duplicated().sum()                       # Count duplicates
df[df.duplicated()]                         # View duplicate rows
df.drop_duplicates(inplace=True)            # Remove duplicates

# ---- DATA TYPES ----
df.dtypes                                   # Check data types
df['col'] = pd.to_datetime(df['col'])       # Convert to datetime

# ---- TEXT CLEANING ----
df['col'] = df['col'].str.strip()           # Remove extra spaces
df['col'] = df['col'].str.title()           # Convert to Title Case
df['col'] = df['col'].str.strip().str.title()  # Both together!

# ---- VERIFY ----
df.info()                                   # Full overview
df.isnull().sum()                           # Confirm no missing
df.duplicated().sum()                       # Confirm no duplicates
```

---

**Next Lesson:** Data Transformation & Feature Engineering — Creating new columns and transforming existing ones for deeper analysis!

---

*📓 Notebook created for the Retail Sales Analysis Project — Data Science Batch*